// Generated by `bun tools/help-article.ts freeze <phrase> …`. Do not edit by hand.
//
// How often each phrase the register cites occurs in the game's published help.
// Counts only — the help's own sentences stay out of this repository (NOTICE.md),
// and a count is our measurement of the article rather than a piece of it.
//
// What it is for: a claim in `docs/protocol-keys.md` that the help does **or does
// not** document a key is re-earned against this table on every gate. A negative
// recorded from a search nobody re-runs is how four keys came to be filed as
// undocumented while the help described all four — see the notice in that file.

export const FROZEN_HELP_PHRASES = {
  article: "372",
  /** When the dump these counts were taken from was fetched, not when it was read. */
  fetchedAt: "2026-08-09T21:49:44.598Z",
  counts: {
    "( skillId )": 0,
    "( tspell )": 0,
    "absorb": 19,
    "absorbm": 3,
    "acdmg": 11,
    "acdmg_destroyed": 0,
    "active_absorbdest_per": 1,
    "active_block_per": 4,
    "active_decblock_per": 11,
    "active_decblock_per-enemies": 5,
    "alllowdmg": 1,
    "allslow_per": 8,
    "aura-ac_per": 2,
    "aura-resall": 1,
    "aura-sa_per": 8,
    "blok": 119,
    "cleanse": 1,
    "combo-max": 6,
    "crit": 98,
    "critpoison_per": 8,
    "critslow_per": 9,
    "curse": 5,
    "destroyed": 0,
    "dispel": 0,
    "energy": 11,
    "engback": 2,
    "exp": 17,
    "facade": 1,
    "freeze": 4,
    "healall_per": 3,
    "holytouch": 1,
    "injure": 3,
    "mana": 43,
    "pierce": 10,
    "poison_lowdmg_per-enemies": 14,
    "prepare": 0,
    "resdmg": 3,
    "shout": 3,
    "skillId": 0,
    "step": 4,
    "stun": 18,
    "superspell": 0,
    "superspell-dispel": 0,
    "tenacity": 0,
    "tspell": 0,
    "txt": 0,
    "verycrit": 2,
  },
} as const;
