// Generated by `deno task game:skills freeze`. Do not edit by hand.
//
// The skills whose effects reach more than one combatant, and the turns the published
// table states each runs for. `src/core/aura-standing.ts` owns which keys those are.
//
// A shout states a count of characters where the others state a share, so it is
// frozen apart: its own turns, and the fewest it covers at any level.

export const FROZEN_AURA_TURNS = {
    /** When the page these were read from was fetched, not when a person read it. */
    fetchedAt: "2026-09-08T13:38:49.115Z",
    skills: [
        { id: 25, turns: 3 },
        { id: 76, turns: 8 },
        { id: 89, turns: 8 },
        { id: 123, turns: 8 },
        { id: 188, turns: 5 },
        { id: 206, turns: 2 },
        { id: 212, turns: 8 },
        { id: 219, turns: 8 },
        { id: 244, turns: 8 },
        { id: 264, turns: 8 },
        { id: 285, turns: 40 },
        { id: 291, turns: 5 },
        { id: 298, turns: 8 },
    ],
    shouts: [
        { id: 25, turns: 3, coverageMinimum: 6 },
        { id: 188, turns: 3, coverageMinimum: 6 },
    ],
} as const;
