// Generated by `deno task game:skills freeze`. Do not edit by hand.
//
// The skills whose effects reach more than one combatant, and the turns the published table
// states each runs for. `src/core/aura-standing.ts` owns which keys those are.

export const FROZEN_AURA_TURNS = {
    /** When the page these were read from was fetched, not when a person read it. */
    fetchedAt: "2026-09-03T20:35:12.415Z",
    skills: [
        { id: 25, turns: 3 },
        { id: 76, turns: 8 },
        { id: 89, turns: 8 },
        { id: 123, turns: 8 },
        { id: 188, turns: 5 },
        { id: 206, turns: 2 },
        { id: 212, turns: 8 },
        { id: 219, turns: 8 },
        { id: 244, turns: 8 },
        { id: 264, turns: 8 },
        { id: 285, turns: 40 },
        { id: 291, turns: 5 },
        { id: 298, turns: 8 },
    ],
} as const;
