// Generated by `deno task game:skills freeze`. Do not edit by hand.
//
// The skills the published table grants an attack beyond their own, and the fewest it
// grants at any level. `src/core/fight-decoder.ts` is what reads them: an announcement
// reaches one blow further for each.

export const FROZEN_BLOWS_GRANTED = {
    /** When the page these were read from was fetched, not when a person read it. */
    fetchedAt: "2026-09-15T13:20:17.965Z",
    skills: [
        { id: 97, blowsGrantedMinimum: 1 },
        { id: 239, blowsGrantedMinimum: 1 },
        { id: 283, blowsGrantedMinimum: 2 },
    ],
} as const;
