// Generated by `deno task game:buffs freeze`. Do not edit by hand.
//
// The statuses a combatant's `buffs` mask is read by, in the order the client registers
// them, so the position is the bit. `tools/buff-bit-table.ts` says what they are lifted from.

export const FROZEN_BUFF_BITS = {
    gameBuild: "Bb28FQty",
    bits: [
        "deep_wound",
        "wound",
        "critical_deep_wound",
        "poisoned",
        "fire",
        "swow_down",
        "speed_up",
        "frostbite",
        "shock",
    ],
} as const;
