// Generated by `deno task game:skills freeze`. Do not edit by hand.
//
// Ids, effect keys and stated turns only, and `tools/skill-table.ts` says why the description
// column the page serves beside them stays in the cache.

export const FROZEN_SKILL_DURATIONS = {
    /** When the page these were read from was fetched, not when a person read it. */
    fetchedAt: "2026-09-03T20:35:12.415Z",
    skills: [
        {
            id: 7,
            effects: [
                { key: "critmval_l", turns: [] },
                { key: "absagain_per", turns: [] },
                { key: "redstun", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 8,
            effects: [
                { key: "manaendest", turns: [] },
                { key: "dmg-target_absolute", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 9,
            effects: [
                { key: "critmval_c", turns: [] },
                { key: "absagain_per", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 11,
            effects: [
                { key: "manabon", turns: [] },
                { key: "manastr", turns: [] },
                { key: "managain", turns: [] },
            ],
        },
        {
            id: 12,
            effects: [
                { key: "absorbm_per", turns: [] },
                { key: "absorb_per", turns: [] },
                { key: "absagain_per", turns: [] },
            ],
        },
        {
            id: 14,
            effects: [
                { key: "slowfreeze_per", turns: [2] },
                { key: "freeze", turns: [] },
                { key: "frostbon", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 15,
            effects: [
                { key: "critval", turns: [] },
                { key: "critsa", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 18,
            effects: [
                { key: "critval", turns: [] },
                { key: "dmg_to_npc_per", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 20,
            effects: [
                { key: "contra", turns: [] },
                { key: "rage", turns: [] },
                { key: "resfire", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "reslight", turns: [] },
                { key: "str2h", turns: [] },
            ],
        },
        {
            id: 21,
            effects: [
                { key: "adddmg_fire-perw", turns: [] },
                { key: "dmg-target_fire-perw", turns: [2, 3, 4] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 22,
            effects: [
                { key: "stun", turns: [] },
                { key: "active_decblock_per", turns: [] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "str2h", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 23,
            effects: [
                { key: "active_acdmg_physical-perw", turns: [] },
                { key: "active_acdmg_per", turns: [] },
                { key: "lowdmg_enemy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "energy", turns: [] },
                { key: "str2h", turns: [] },
            ],
        },
        {
            id: 24,
            effects: [
                { key: "hpbon", turns: [] },
            ],
        },
        {
            id: 25,
            effects: [
                { key: "shout", turns: [3] },
                { key: "acshield_per", turns: [] },
                { key: "active_redstun", turns: [2] },
                { key: "aura-adddmg2_per-meele_physical", turns: [2] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 26,
            effects: [
                { key: "adddmg_fire-perw", turns: [] },
                { key: "dmg-target_fire-perw", turns: [2] },
                { key: "active_decevade_per", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "firebon", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 27,
            effects: [
                { key: "parry", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 29,
            effects: [
                { key: "redstun", turns: [] },
                { key: "redslow", turns: [] },
                { key: "ac2_per", turns: [] },
            ],
        },
        {
            id: 30,
            effects: [
                { key: "critrage_perw", turns: [] },
                { key: "slow", turns: [] },
                { key: "str2h", turns: [] },
            ],
        },
        {
            id: 31,
            effects: [
                { key: "wounddmgbon_perw", turns: [] },
                { key: "acdmg", turns: [] },
            ],
        },
        {
            id: 32,
            effects: [
                { key: "critwound", turns: [] },
                { key: "str1h", turns: [] },
                { key: "str2h", turns: [] },
            ],
        },
        {
            id: 33,
            effects: [
                { key: "critslow_per", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 34,
            effects: [
                { key: "resfire_per", turns: [8] },
                { key: "resfrost_per", turns: [8] },
                { key: "reslight_per", turns: [8] },
                { key: "antidote", turns: [8] },
                { key: "achpp_per", turns: [8] },
                { key: "energy", turns: [] },
                { key: "red-sa", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 36,
            effects: [
                { key: "decevade_per", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 37,
            effects: [
                { key: "distract", turns: [] },
            ],
        },
        {
            id: 38,
            effects: [
                { key: "sa_per", turns: [] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 39,
            effects: [
                { key: "perdmg", turns: [3] },
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 41,
            effects: [
                { key: "disturb_crit", turns: [] },
                { key: "disturb_pierce", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 42,
            effects: [
                { key: "lastcrit", turns: [] },
            ],
        },
        {
            id: 43,
            effects: [
                { key: "vamp_time_per", turns: [8] },
                { key: "resfire_per", turns: [8] },
                { key: "resfrost_per", turns: [8] },
                { key: "reslight_per", turns: [8] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 44,
            effects: [
                { key: "engback", turns: [] },
                { key: "blok_per", turns: [] },
            ],
        },
        {
            id: 45,
            effects: [
                { key: "resfire", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "reslight", turns: [] },
            ],
        },
        {
            id: 46,
            effects: [
                { key: "arrowblock", turns: [] },
                { key: "redabdest_per", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 47,
            effects: [
                { key: "resfire", turns: [] },
                { key: "firebon", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "frostbon", turns: [] },
                { key: "reslight", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 49,
            effects: [
                { key: "contra", turns: [] },
                { key: "manabon", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 50,
            effects: [
                { key: "lightshield_per", turns: [8] },
                { key: "active_redstun", turns: [8] },
                { key: "red-sa", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 53,
            effects: [
                { key: "lightshield_per", turns: [8] },
                { key: "ac_per", turns: [8] },
                { key: "red-sa", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 54,
            effects: [
                { key: "lastcrit", turns: [] },
            ],
        },
        {
            id: 55,
            effects: [
                { key: "lightshield_per", turns: [8] },
                { key: "antidote", turns: [8] },
                { key: "red-sa", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 56,
            effects: [
                { key: "perdmg", turns: [3] },
                { key: "disturb_pierce", turns: [3] },
                { key: "combo_lowdmg_enemy", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 58,
            effects: [
                { key: "slowfreeze_per", turns: [2] },
                { key: "freeze", turns: [] },
                { key: "active_absorbdest_per", turns: [] },
                { key: "mana", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 59,
            effects: [
                { key: "critmval_f", turns: [] },
                { key: "absagain_per", turns: [] },
                { key: "absorbd", turns: [] },
                { key: "ac", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 61,
            effects: [
                { key: "sa1", turns: [] },
            ],
        },
        {
            id: 62,
            effects: [
                { key: "sa-clothes", turns: [] },
            ],
        },
        {
            id: 64,
            effects: [
                { key: "pierce", turns: [] },
            ],
        },
        {
            id: 65,
            effects: [
                { key: "of-crit", turns: [] },
                { key: "of-critval", turns: [] },
                { key: "of-str", turns: [] },
            ],
        },
        {
            id: 66,
            effects: [
                { key: "woundchance", turns: [] },
                { key: "wounddmgbon_perw", turns: [] },
            ],
        },
        {
            id: 67,
            effects: [
                { key: "vulture_perw", turns: [] },
            ],
        },
        {
            id: 68,
            effects: [
                { key: "active_acdmg_per", turns: [] },
                { key: "dmg_evade_hpp-target_light", turns: [3] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 69,
            effects: [
                { key: "manarestore_per", turns: [] },
            ],
        },
        {
            id: 70,
            effects: [
                { key: "dmg_evade_hpp-target_light", turns: [3] },
                { key: "active_acdmg_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "active_add_light_cumulaction", turns: [] },
                { key: "mana", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 71,
            effects: [
                { key: "energybon", turns: [] },
                { key: "energygain", turns: [] },
            ],
        },
        {
            id: 72,
            effects: [
                { key: "woundchance", turns: [] },
                { key: "wounddmgbon_perw", turns: [] },
            ],
        },
        {
            id: 73,
            effects: [
                { key: "energyrestore_per", turns: [] },
            ],
        },
        {
            id: 75,
            effects: [
                { key: "adrenalin_evade", turns: [] },
            ],
        },
        {
            id: 76,
            effects: [
                { key: "aura-ac_per", turns: [8] },
                { key: "aura-resall", turns: [8] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 77,
            effects: [
                { key: "critmval_f", turns: [] },
                { key: "manabon", turns: [] },
                { key: "resdmg", turns: [] },
            ],
        },
        {
            id: 78,
            effects: [
                { key: "heal_per", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 79,
            effects: [
                { key: "healall_per", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 81,
            effects: [
                { key: "bandage_per", turns: [] },
                { key: "active_redstun", turns: [2] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 82,
            effects: [
                { key: "poisonbon_poison-perw", turns: [] },
                { key: "sa_per", turns: [] },
                { key: "lowdmg_enemy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 84,
            effects: [
                { key: "of-wounddmgbon_perw", turns: [] },
                { key: "woundchance", turns: [] },
            ],
        },
        {
            id: 85,
            effects: [
                { key: "red-sa", turns: [] },
                { key: "active_decevade_per", turns: [] },
                { key: "combo_energyrestore_per", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 86,
            effects: [
                { key: "slowfreeze_per", turns: [2] },
                { key: "freeze", turns: [] },
                { key: "active_absorbdest_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 87,
            effects: [
                { key: "critpoison", turns: [] },
                { key: "actdmg", turns: [] },
            ],
        },
        {
            id: 88,
            effects: [
                { key: "fastarrow", turns: [] },
            ],
        },
        {
            id: 89,
            effects: [
                { key: "aura-sa_per", turns: [8] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 90,
            effects: [
                { key: "absorb_per", turns: [] },
                { key: "absorbm_per", turns: [] },
                { key: "absagain_per", turns: [] },
            ],
        },
        {
            id: 92,
            effects: [
                { key: "sunshield_per", turns: [5] },
                { key: "active_crit", turns: [5] },
                { key: "mana", turns: [] },
                { key: "red-sa", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 94,
            effects: [
                { key: "of-thirdatt", turns: [] },
                { key: "of-str", turns: [] },
            ],
        },
        {
            id: 95,
            effects: [
                { key: "perdmg", turns: [] },
                { key: "combo_lowdmg_enemy", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 96,
            effects: [
                { key: "active_wound_per", turns: [] },
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 97,
            effects: [
                { key: "energy", turns: [] },
                { key: "lowdmg_self", turns: [] },
                { key: "add_attacks", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 98,
            effects: [
                { key: "critslow_per", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 99,
            effects: [
                { key: "adddmg_fire-perw", turns: [] },
                { key: "dmg-target_fire-perw", turns: [2] },
                { key: "active_decevade_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 100,
            effects: [
                { key: "parry", turns: [] },
                { key: "pcontra", turns: [] },
            ],
        },
        {
            id: 101,
            effects: [
                { key: "pierceb", turns: [] },
            ],
        },
        {
            id: 102,
            effects: [
                { key: "stinkbomb_crit", turns: [8] },
                { key: "stinkbomb_pierce", turns: [8] },
                { key: "taken_dmg_per", turns: [8] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 103,
            effects: [
                { key: "adrenalin_evade", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 105,
            effects: [
                { key: "active_crit", turns: [] },
                { key: "active_decevade_per", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 106,
            effects: [
                { key: "dmg_from_npc_per", turns: [] },
                { key: "dmg_from_player_per", turns: [] },
            ],
        },
        {
            id: 107,
            effects: [
                { key: "heal1_per", turns: [] },
            ],
        },
        {
            id: 108,
            effects: [
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "sa_per", turns: [] },
                { key: "active_decblock_per", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "combo-block", turns: [] },
                { key: "str1h", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 109,
            effects: [
                { key: "injure", turns: [] },
            ],
        },
        {
            id: 110,
            effects: [
                { key: "disturb_crit", turns: [3] },
                { key: "disturb_pierce", turns: [3] },
                { key: "lowdmg_enemy", turns: [3] },
                { key: "red-sa", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 111,
            effects: [
                { key: "energyrestore_per", turns: [] },
            ],
        },
        {
            id: 112,
            effects: [
                { key: "active_acdmg_per", turns: [] },
                { key: "dmg_evade_hpp-target_light", turns: [3] },
                { key: "active_decblock_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "active_add_light_cumulaction", turns: [] },
                { key: "mana", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 113,
            effects: [
                { key: "active_crit", turns: [2] },
                { key: "energy", turns: [] },
                { key: "combo-crit", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 119,
            effects: [
                { key: "reddest_per", turns: [] },
                { key: "dmg_from_player_per", turns: [] },
            ],
        },
        {
            id: 120,
            effects: [
                { key: "redacdmg_per", turns: [] },
                { key: "dmg_from_player_per", turns: [] },
            ],
        },
        {
            id: 123,
            effects: [
                { key: "allslow_per", turns: [8] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 125,
            effects: [
                { key: "critsa", turns: [] },
                { key: "of-str", turns: [] },
            ],
        },
        {
            id: 127,
            effects: [
                { key: "dmg-swing_absolute-perw", turns: [] },
                { key: "swing", turns: [] },
                { key: "dmg_from_npc_per", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 129,
            effects: [
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "active_decevade_per", turns: [] },
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "active_wound_per", turns: [] },
            ],
        },
        {
            id: 130,
            effects: [
                { key: "sa2_per", turns: [8] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 131,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
            ],
        },
        {
            id: 166,
            effects: [
                { key: "heal_per-enemies", turns: [] },
            ],
        },
        {
            id: 167,
            effects: [
                { key: "critslow_per", turns: [] },
            ],
        },
        {
            id: 168,
            effects: [
                { key: "crit", turns: [] },
            ],
        },
        {
            id: 173,
            effects: [
                { key: "injure", turns: [] },
            ],
        },
        {
            id: 174,
            effects: [
                { key: "resfrost", turns: [] },
                { key: "pierce", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 178,
            effects: [
                { key: "adddmg_physical-perw", turns: [] },
                { key: "active_decevade_per", turns: [] },
                { key: "active_decblock_per", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 179,
            effects: [
                { key: "resfire", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "reslight", turns: [] },
            ],
        },
        {
            id: 180,
            effects: [
                { key: "rage", turns: [] },
                { key: "adrenalin_reddest", turns: [] },
            ],
        },
        {
            id: 181,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
            ],
        },
        {
            id: 182,
            effects: [
                { key: "active_crit", turns: [3] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 183,
            effects: [
                { key: "critslow_per", turns: [] },
            ],
        },
        {
            id: 184,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
            ],
        },
        {
            id: 185,
            effects: [
                { key: "energybon", turns: [] },
                { key: "energygain", turns: [] },
                { key: "manabon", turns: [] },
                { key: "manastr", turns: [] },
                { key: "managain", turns: [] },
            ],
        },
        {
            id: 186,
            effects: [
                { key: "decevade_per", turns: [] },
            ],
        },
        {
            id: 187,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
            ],
        },
        {
            id: 188,
            effects: [
                { key: "shout", turns: [3] },
                { key: "active_decblock_per-enemies", turns: [5] },
                { key: "alllowdmg", turns: [5] },
                { key: "red-sa", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 189,
            effects: [
                { key: "parry", turns: [] },
            ],
        },
        {
            id: 190,
            effects: [
                { key: "critmval_c", turns: [] },
                { key: "slow", turns: [] },
            ],
        },
        {
            id: 191,
            effects: [
                { key: "perdmg", turns: [8] },
                { key: "en-regen", turns: [8] },
                { key: "combo_heal_per", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 192,
            effects: [
                { key: "manarestore_per", turns: [] },
                { key: "energyrestore_per", turns: [] },
            ],
        },
        {
            id: 193,
            effects: [
                { key: "critmval_f", turns: [] },
                { key: "heal1_per", turns: [] },
                { key: "absorbd", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 194,
            effects: [
                { key: "critmval_l", turns: [] },
                { key: "critpierce_per", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 195,
            effects: [
                { key: "critmval_c", turns: [] },
                { key: "crit", turns: [] },
                { key: "heal1_per", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 196,
            effects: [
                { key: "hpbon", turns: [] },
            ],
        },
        {
            id: 197,
            effects: [
                { key: "disturb_crit", turns: [] },
                { key: "disturb_pierce", turns: [] },
                { key: "lowdmg_enemy", turns: [2] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
            ],
        },
        {
            id: 198,
            effects: [
                { key: "redslow", turns: [] },
                { key: "redstun", turns: [] },
                { key: "ac2_per", turns: [] },
            ],
        },
        {
            id: 199,
            effects: [
                { key: "healall_per", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 200,
            effects: [
                { key: "heal1_per", turns: [] },
                { key: "arrowblock", turns: [] },
            ],
        },
        {
            id: 201,
            effects: [
                { key: "rage_3turns", turns: [] },
                { key: "decevade_per", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 202,
            effects: [
                { key: "lightshield_per", turns: [8] },
                { key: "antidote", turns: [8] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 203,
            effects: [
                { key: "adddmg_physical-perw", turns: [] },
                { key: "dmg_evade_hpp-target", turns: [8] },
                { key: "combo-skill", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 204,
            effects: [
                { key: "sa_per", turns: [] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 205,
            effects: [
                { key: "engback", turns: [] },
            ],
        },
        {
            id: 206,
            effects: [
                { key: "acshield_per", turns: [] },
                { key: "active_block_per", turns: [] },
                { key: "active_redstun", turns: [2] },
                { key: "active_crit-allies", turns: [2] },
                { key: "combo_heal_per", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 207,
            effects: [
                { key: "str1h", turns: [] },
                { key: "str2h", turns: [] },
                { key: "critval", turns: [] },
            ],
        },
        {
            id: 208,
            effects: [
                { key: "blok_per", turns: [] },
                { key: "arrowblock", turns: [] },
                { key: "combo-block", turns: [] },
                { key: "decevade_per", turns: [] },
            ],
        },
        {
            id: 209,
            effects: [
                { key: "sa_per", turns: [] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 210,
            effects: [
                { key: "active_acdmg_per", turns: [] },
                { key: "sa_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 211,
            effects: [
                { key: "injure", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 212,
            effects: [
                { key: "critval-allies", turns: [8] },
                { key: "critmval-allies", turns: [8] },
                { key: "perdmg-allies", turns: [8] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 213,
            effects: [
                { key: "energybon", turns: [] },
                { key: "energygain", turns: [] },
            ],
        },
        {
            id: 214,
            effects: [
                { key: "redslow", turns: [] },
                { key: "evade_per", turns: [] },
            ],
        },
        {
            id: 215,
            effects: [
                { key: "evade_per", turns: [] },
            ],
        },
        {
            id: 216,
            effects: [
                { key: "engback", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 217,
            effects: [
                { key: "sa_per", turns: [] },
                { key: "perdmg", turns: [8] },
                { key: "resfire_per", turns: [8] },
                { key: "resfrost_per", turns: [8] },
                { key: "reslight_per", turns: [8] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 218,
            effects: [
                { key: "redslow", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 219,
            effects: [
                { key: "lowheal_per-enemies", turns: [8] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 220,
            effects: [
                { key: "energyrestore_per", turns: [] },
            ],
        },
        {
            id: 221,
            effects: [
                { key: "critval", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 222,
            effects: [
                { key: "sa2_per", turns: [2] },
                { key: "combo_lowdmg_enemy", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 223,
            effects: [
                { key: "disturb_crit", turns: [] },
                { key: "disturb_pierce", turns: [] },
                { key: "lowdmg_enemy", turns: [2] },
                { key: "sa_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 224,
            effects: [
                { key: "energyout", turns: [5] },
                { key: "dmg-target_absolute", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 225,
            effects: [
                { key: "critslow_per", turns: [] },
                { key: "str1h", turns: [] },
            ],
        },
        {
            id: 226,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
            ],
        },
        {
            id: 227,
            effects: [
                { key: "adrenalin_sa", turns: [] },
                { key: "of-str", turns: [] },
            ],
        },
        {
            id: 228,
            effects: [
                { key: "rage_3turns", turns: [] },
            ],
        },
        {
            id: 229,
            effects: [
                { key: "critpoison", turns: [] },
                { key: "actdmg", turns: [] },
            ],
        },
        {
            id: 230,
            effects: [
                { key: "resfire", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "reslight", turns: [] },
            ],
        },
        {
            id: 231,
            effects: [
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 232,
            effects: [
                { key: "poisonbon_poison-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "lowdmg_enemy", turns: [] },
                { key: "combo-skill", turns: [] },
            ],
        },
        {
            id: 233,
            effects: [
                { key: "resfire", turns: [] },
                { key: "resfrost", turns: [] },
                { key: "reslight", turns: [] },
            ],
        },
        {
            id: 234,
            effects: [
                { key: "energybon", turns: [] },
                { key: "energygain", turns: [] },
            ],
        },
        {
            id: 235,
            effects: [
                { key: "evade_per", turns: [] },
            ],
        },
        {
            id: 236,
            effects: [
                { key: "poison_lowdmg_per-enemies", turns: [] },
            ],
        },
        {
            id: 237,
            effects: [
                { key: "bandage_per", turns: [] },
                { key: "resfire_per", turns: [2] },
                { key: "resfrost_per", turns: [2] },
                { key: "reslight_per", turns: [2] },
                { key: "cooldown", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 238,
            effects: [
                { key: "removestun-allies", turns: [] },
                { key: "removedot-allies", turns: [] },
                { key: "red-sa", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 239,
            effects: [
                { key: "energy", turns: [] },
                { key: "lowdmg_self", turns: [] },
                { key: "add_attacks", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 240,
            effects: [
                { key: "sa-clothes", turns: [] },
                { key: "redslow", turns: [] },
            ],
        },
        {
            id: 241,
            effects: [
                { key: "poison_lowdmg_per-enemies", turns: [] },
                { key: "combo-pierce", turns: [] },
            ],
        },
        {
            id: 242,
            effects: [
                { key: "heal_per-enemies", turns: [] },
            ],
        },
        {
            id: 243,
            effects: [
                { key: "energybon", turns: [] },
                { key: "energygain", turns: [] },
                { key: "manabon", turns: [] },
                { key: "manastr", turns: [] },
                { key: "managain", turns: [] },
            ],
        },
        {
            id: 244,
            effects: [
                { key: "critval-enemies", turns: [8] },
                { key: "critmval-enemies", turns: [8] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 245,
            effects: [
                { key: "wounddmgbon_perw", turns: [] },
                { key: "woundchance", turns: [] },
                { key: "combo-wound", turns: [] },
            ],
        },
        {
            id: 246,
            effects: [
                { key: "combo_dmg_hpp-target", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 247,
            effects: [
                { key: "lowdmg_enemy", turns: [3] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 248,
            effects: [
                { key: "heal_per", turns: [] },
                { key: "cooldown", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 249,
            effects: [
                { key: "manarestore_per", turns: [] },
                { key: "energyrestore_per", turns: [] },
            ],
        },
        {
            id: 250,
            effects: [
                { key: "critmval_f", turns: [] },
                { key: "lastcrit", turns: [] },
                { key: "parry", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 251,
            effects: [
                { key: "critmval_l", turns: [] },
                { key: "pierce", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 252,
            effects: [
                { key: "critmval_c", turns: [] },
                { key: "critpoison", turns: [] },
                { key: "crit", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 253,
            effects: [
                { key: "slow", turns: [] },
                { key: "critval", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 254,
            effects: [
                { key: "red-sa", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 255,
            effects: [
                { key: "fastarrow", turns: [] },
                { key: "pierce", turns: [] },
                { key: "combo-crit", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 256,
            effects: [
                { key: "decevade_per", turns: [] },
                { key: "redstun", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 257,
            effects: [
                { key: "vulture_perw", turns: [] },
                { key: "agi", turns: [] },
            ],
        },
        {
            id: 258,
            effects: [
                { key: "decblock_per", turns: [] },
            ],
        },
        {
            id: 259,
            effects: [
                { key: "act", turns: [] },
                { key: "woundred", turns: [] },
                { key: "evade_per", turns: [] },
            ],
        },
        {
            id: 260,
            effects: [
                { key: "resfire", turns: [] },
                { key: "redabdest_per", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 261,
            effects: [
                { key: "reslight", turns: [] },
                { key: "crush_dmg_physical", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 262,
            effects: [
                { key: "pierce", turns: [] },
                { key: "combo-crit", turns: [] },
                { key: "frostbon", turns: [] },
            ],
        },
        {
            id: 263,
            effects: [
                { key: "hp", turns: [] },
            ],
        },
        {
            id: 264,
            effects: [
                { key: "taken_dmg_per-all", turns: [8] },
                { key: "red-sa", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 265,
            effects: [
                { key: "critpierce_per", turns: [] },
                { key: "woundchance", turns: [] },
            ],
        },
        {
            id: 266,
            effects: [
                { key: "immunity_to_dmg", turns: [2] },
                { key: "cooldown", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 267,
            effects: [
                { key: "decevade_per", turns: [] },
            ],
        },
        {
            id: 268,
            effects: [
                { key: "hp", turns: [] },
                { key: "healpower", turns: [] },
                { key: "dmg_from_player_per", turns: [] },
            ],
        },
        {
            id: 269,
            effects: [
                { key: "ac", turns: [] },
            ],
        },
        {
            id: 270,
            effects: [
                { key: "dmg_to_npc_per", turns: [] },
            ],
        },
        {
            id: 271,
            effects: [
                { key: "active_crit", turns: [2] },
                { key: "sa_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 272,
            effects: [
                { key: "vamp_time_per", turns: [8] },
                { key: "active_crit", turns: [8] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 273,
            effects: [
                { key: "dmg-target_absolute", turns: [] },
                { key: "stealmana_per", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 274,
            effects: [
                { key: "engback", turns: [] },
            ],
        },
        {
            id: 275,
            effects: [
                { key: "heal_per-allies", turns: [] },
            ],
        },
        {
            id: 276,
            effects: [
                { key: "hp_per-allies", turns: [] },
            ],
        },
        {
            id: 277,
            effects: [
                { key: "redslow", turns: [] },
                { key: "arrowblock", turns: [] },
                { key: "frostbon", turns: [] },
                { key: "lightbon", turns: [] },
                { key: "firebon", turns: [] },
            ],
        },
        {
            id: 278,
            effects: [
                { key: "crush_dmg_physical", turns: [] },
                { key: "critpoison", turns: [] },
                { key: "critval", turns: [] },
            ],
        },
        {
            id: 279,
            effects: [
                { key: "pierce", turns: [] },
                { key: "acdmg", turns: [] },
            ],
        },
        {
            id: 283,
            effects: [
                { key: "add_attacks", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 284,
            effects: [
                { key: "crit", turns: [] },
            ],
        },
        {
            id: 285,
            effects: [
                { key: "active_decblock_per-enemies", turns: [40] },
            ],
        },
        {
            id: 286,
            effects: [
                { key: "vamp_time_per", turns: [50] },
            ],
        },
        {
            id: 287,
            effects: [
                { key: "dmg-target_physical", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 288,
            effects: [
                { key: "active_add_light_cumulaction", turns: [] },
                { key: "dmg-force-4_light-perw", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 289,
            effects: [
                { key: "slowfreeze_per", turns: [2] },
                { key: "freeze", turns: [] },
                { key: "active_absorbdest_per", turns: [] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 290,
            effects: [
                { key: "lightshield_per", turns: [14] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 291,
            effects: [
                { key: "crush_dmg_physical", turns: [] },
                { key: "taken_dmg_per-all", turns: [5] },
                { key: "dmg-target_fire", turns: [5] },
            ],
        },
        {
            id: 292,
            effects: [
                { key: "immunity_to_dmg", turns: [5] },
            ],
        },
        {
            id: 293,
            effects: [
                { key: "dmg_evade_hpp-target_light", turns: [3] },
                { key: "active_acdmg_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "active_add_light_cumulaction", turns: [] },
                { key: "mana", turns: [] },
                { key: "doublecastcost_per", turns: [] },
                { key: "lightbon", turns: [] },
            ],
        },
        {
            id: 294,
            effects: [
                { key: "heal_per", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 295,
            effects: [
                { key: "sa_per", turns: [] },
                { key: "adddmg_physical-perw", turns: [] },
                { key: "energy", turns: [] },
                { key: "combo-skill", turns: [] },
            ],
        },
        {
            id: 296,
            effects: [
                { key: "active_acdmg_per", turns: [] },
                { key: "sa_per", turns: [] },
                { key: "combo-skill", turns: [] },
                { key: "energy", turns: [] },
            ],
        },
        {
            id: 297,
            effects: [
                { key: "sa2_per", turns: [2] },
                { key: "combo_lowdmg_enemy", turns: [] },
                { key: "combo-max", turns: [] },
                { key: "energy", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 298,
            effects: [
                { key: "allslow_per", turns: [8] },
                { key: "mana", turns: [] },
            ],
        },
        {
            id: 299,
            effects: [
                { key: "adddmg_fire-perw", turns: [] },
                { key: "dmg-target_fire-perw", turns: [2, 3, 4] },
                { key: "combo-skill", turns: [] },
                { key: "mana", turns: [] },
                { key: "cooldown", turns: [] },
            ],
        },
        {
            id: 300,
            effects: [
                { key: "dmgmulabsolute", turns: [] },
            ],
        },
        {
            id: 301,
            effects: [
                { key: "critmval_l", turns: [] },
                { key: "acdmg", turns: [] },
            ],
        },
        {
            id: 302,
            effects: [
                { key: "critpoison", turns: [] },
            ],
        },
        {
            id: 303,
            effects: [
                { key: "energybon", turns: [] },
                { key: "evade_per", turns: [] },
            ],
        },
        {
            id: 304,
            effects: [
                { key: "dmgmulabsolute", turns: [] },
            ],
        },
        {
            id: 305,
            effects: [
                { key: "lowdmg_enemy", turns: [] },
            ],
        },
        {
            id: 306,
            effects: [
                { key: "critpoison", turns: [] },
            ],
        },
    ],
} as const;
