/**
 * The statuses a combatant's `buffs` mask is read by, lifted from the production bundle. A payload
 * restates the mask as one integer per combatant, and the client turns it into icons by walking
 * one bit per registered status, so the order they are registered in is what a bit means. Names
 * only: the sentences the game composes from them stay in the cache (`NOTICE.md`).
 *
 *     deno task margonem:buffs [freeze]
 */

import { assert, assertStrictEquals } from "@std/assert";
import { encodeJson } from "#/libs/json-text.ts";
import { formatInteger } from "#/libs/number-text.ts";
import { getEndOfRun, isWhitespaceAt, lookupQuotedLiteral } from "#/libs/text-walk.ts";
import {
    MARGONEM_CHANNEL,
    readCachedBundle,
    requireCachedBuild,
} from "./margonem-client-source.ts";
import { type FrozenFiles, prepareFrozenFiles, writeFrozenFiles } from "./frozen-files.ts";
import { BuffBitTableError } from "./margometer-tool-error.ts";

/**
 * ⚠️ **The array is matched by shape, and a minifier is why.** The development bundle names it
 * `buffNames`; production build `Bb28FQty` calls it `ae`, so a name-anchored walk would read the
 * table off a channel that decides nothing. No build renames the entry: a name, nothing, a class.
 * The development bundle is unminified, so space may stand between the arguments.
 */
const NOTHING_ARGUMENT = "null";
const ARGUMENT_SEPARATOR = ",";
const ROLE = "buff";
const CALL_OPEN = "(";
const CALL_CLOSE = ")";
/** A mask arrives as one integer, so a bit past the thirty-second is not one this reader holds. */
export const STATUS_BITS_MAXIMUM = 32;
/**
 * Past the number of places `null` occurs in a bundle, so the walk stays bounded: 3,989 in
 * production `Bb28FQty` and 4,081 in development `CzdTQ32j` (2026-09-27).
 */
const LOOKS_MAXIMUM = 65_536;
/** Past the distance from an entry's opening bracket to its arguments, for the same reason. */
const WALK_BACK_MAXIMUM = 256;
const FROZEN_PATH = "frozen/buff-bits.ts";
/** The field the reading is dated by, exported so a test holds the frozen file to it. */
export const FROZEN_DATE_FIELD = "gameBuild";
/** What stands over the frozen table, exported so a guard holds the file to its generator. */
export const FROZEN_BUFF_BANNER =
    `// Generated by \`deno task margonem:buffs freeze\`. Do not edit by hand.
//
// The statuses a combatant's \`buffs\` mask is read by, in the order the client registers
// them, so the position is the bit. \`tools/buff-bit-table.ts\` says what they are lifted from.
`;

/** The bit order written to `frozen/`, where it moved. */
export function writeFrozenBuffBits(): FrozenFiles {
    const frozen = prepareFrozenBuffBits();
    writeFrozenFiles(frozen);
    return frozen;
}

/** The bit order the cached bundle gives, dated by the first build that gave it (ADR 0011). */
export function prepareFrozenBuffBits(): FrozenFiles {
    const build = requireCachedBuild();
    const bits = requireBuffBits(readCachedBundle(MARGONEM_CHANNEL.production));
    assert(bits.length > 0, "a table that is frozen counts something");
    return prepareFrozenFiles(
        [FROZEN_PATH],
        FROZEN_DATE_FIELD,
        build,
        bits.length,
        (date) => [encodeFrozenBuffModule(date, bits)],
    );
}

export function encodeFrozenBuffModule(build: string, bits: readonly string[]): string {
    const written = bits.map((name) => `        ${encodeRequiredText(name)},`).join("\n");
    assert(written.length > 0, "a table that is written down says something");
    assert(build.length > 0, "and is dated by the build it was lifted from");
    return `${FROZEN_BUFF_BANNER}
export const FROZEN_BUFF_BITS = {
    ${FROZEN_DATE_FIELD}: ${encodeRequiredText(build)},
    bits: [
${written}
    ],
} as const;
`;
}

/** One bit's name as the text it is written down as, or a refusal branded as this tool's. */
function encodeRequiredText(name: string): string {
    const text = encodeJson(name, 0);
    if (text instanceof Error) {
        throw new BuffBitTableError("a name of the table cannot be written", { cause: text });
    }
    return text;
}

/**
 * Every status the client registers, in source order, which is bit order. A build registering
 * none is one this walk no longer recognises, and it refuses rather than freezing an empty table:
 * an empty reading looks exactly like a game that dropped the feature.
 */
export function requireBuffBits(bundle: string): string[] {
    const names: string[] = [];
    let nothingAt = bundle.indexOf(NOTHING_ARGUMENT);
    for (let look = 0; look < LOOKS_MAXIMUM; look += 1) {
        if (nothingAt === -1) break;
        const name = lookupRegisteredStatusName(bundle, nothingAt);
        if (name !== null) {
            assert(names.length < STATUS_BITS_MAXIMUM, "a mask holds no more bits than an integer");
            names.push(name);
        }
        nothingAt = bundle.indexOf(NOTHING_ARGUMENT, nothingAt + 1);
    }
    if (names.length === 0) {
        throw new BuffBitTableError("no status is registered in the bundle — the client changed");
    }
    assertStrictEquals(new Set(names).size, names.length, "each status is named at one position");
    return names;
}

/**
 * The name registered by the entry whose `null` sits at `nothingAt`, or null where that is some
 * other call. Read forwards from the bracket rather than back from the comma: a literal is a
 * literal only where something says where it opened, and the bracket is that thing.
 */
function lookupRegisteredStatusName(bundle: string, nothingAt: number): string | null {
    assert(nothingAt >= 0, "an entry is looked for inside the bundle");
    const after = getEndOfRun(bundle, nothingAt + NOTHING_ARGUMENT.length, isWhitespaceAt);
    if (bundle.charAt(after) !== ARGUMENT_SEPARATOR) return null;
    const role = lookupQuotedLiteral(bundle, getEndOfRun(bundle, after + 1, isWhitespaceAt));
    if (role === null) return null;
    if (role.text !== ROLE) return null;
    if (bundle.charAt(getEndOfRun(bundle, role.end, isWhitespaceAt)) !== CALL_CLOSE) return null;
    const separator = bundle.lastIndexOf(ARGUMENT_SEPARATOR, nothingAt);
    if (separator === -1) return null;
    if (getEndOfRun(bundle, separator + 1, isWhitespaceAt) !== nothingAt) return null;
    const open = bundle.lastIndexOf(CALL_OPEN, separator);
    if (open === -1) return null;
    if (open < nothingAt - WALK_BACK_MAXIMUM) return null;
    const name = lookupQuotedLiteral(bundle, getEndOfRun(bundle, open + 1, isWhitespaceAt));
    if (name === null) return null;
    if (getEndOfRun(bundle, name.end, isWhitespaceAt) !== separator) return null;
    if (name.text.length === 0) return null;
    return name.text;
}

if (import.meta.main) {
    if (Deno.args.includes("freeze")) {
        const frozen = writeFrozenBuffBits();
        const count = formatInteger(frozen.count);
        const moved = frozen.hasMoved ? "froze" : "unchanged:";
        console.log(`${moved} ${count} bits from build ${frozen.date} → ${FROZEN_PATH}`);
    } else {
        const bits = requireBuffBits(readCachedBundle(MARGONEM_CHANNEL.production));
        console.log(`${formatInteger(bits.length)} bits in build ${requireCachedBuild()}`);
        for (const [index, name] of bits.entries()) {
            console.log(`  bit ${formatInteger(index)}  ${name}`);
        }
        console.log(`run with \`freeze\` to write ${FROZEN_PATH}`);
    }
}
