/**
 * The game's published help, cached and searched. It is the only source saying what an effect
 * does (the bundle says which keys exist), and it prints the engine name in parentheses beside the
 * human one, which is what joins an article to a protocol key. Raw slices are printed and never
 * interpreted: a summary that missed a phrase reads exactly like an article that lacks it. What is
 * fetched stays in `.cache/` (`NOTICE.md`).
 *
 *     deno task margonem:help status | fetch | search <phrase> … | freeze [phrase …]
 */

import { assert } from "@std/assert";
import { decodeHtmlText } from "#/libs/html-text.ts";
import { encodeJson, parseJson } from "#/libs/json-text.ts";
import { formatInteger, parseInteger } from "#/libs/number-text.ts";
import * as errors from "#/libs/errors.ts";
import { isRecord } from "#/libs/unknown-value.ts";
import { parseCitedHelpPhrases, REGISTER_PATH } from "./help-claim-register.ts";
import { type FrozenFiles, prepareFrozenFiles, writeFrozenFiles } from "./frozen-files.ts";
import { readMargonemAnswerText } from "./margonem-client-source.ts";
import { HelpArticleError } from "./margometer-tool-error.ts";

export interface CachedHelpArticle {
    article: string;
    url: string;
    fetchedAt: string;
    textPath: string;
    textLength: number;
}

/** A freeze of the counts, with the counts themselves, so a zero can be said aloud. */
export interface FrozenHelpCounts extends FrozenFiles {
    counts: readonly [string, number][];
}

const HELP_HOST = "https://pomoc.margonem.pl";
/**
 * "Mechanika walk", the only article carrying combat mechanics. Exported so the frozen counts are
 * held to naming the article they were taken from: pointing the tool elsewhere once left every
 * count describing a document the tool no longer read.
 */
export const MECHANICS_ARTICLE = "372";
/** Ignored by git, and exported for the reason `tools/margonem-client-source.ts` gives. */
export const CACHE_ROOT = ".cache/help/";
const MANIFEST_NAME = "provenance.json";
const TEXT_NAME = "text.txt";
const FROZEN_PATH = "frozen/help-phrases.ts";
/** The field the reading is dated by, exported so a test holds the frozen file to it. */
export const FROZEN_DATE_FIELD = "fetchedAt";
const INDENT_SPACES = 2;
const MILLISECONDS_PER_DAY = 86_400_000;
/** A week: past it an entry reading "the help is silent" is a false negative wearing a date. */
const STALE_AFTER_DAYS = 7;
/** Six rather than three: a phrase inside a longer word matches it too, and pushes a real hit off. */
const FRAGMENTS_SHOWN = 6;
const CONTEXT_CHARACTERS = 420;
const LOCALE = "pl";
/** What stands over the frozen counts, exported for the reason the key table gives for its own. */
export const FROZEN_HELP_BANNER =
    `// Generated by \`deno task margonem:help freeze <phrase> …\`. Do not edit by hand.
//
// Counts only, and \`tools/help-article.ts\` says what they are counted over and what they are for.
`;

/**
 * The counts written to `frozen/`, where they moved. The phrases are the
 * ones `docs/protocol-keys.md` cites, and any named besides: a re-freeze needs no list retyped, a
 * phrase is counted before a claim cites it, and one no claim cites any more is dropped.
 */
export function writeFrozenHelpCounts(article: string, named: readonly string[]): FrozenHelpCounts {
    const frozen = prepareFrozenHelpCounts(article, named);
    writeFrozenFiles(frozen);
    return frozen;
}

/** The counts the cached dump gives, dated by the first dump that gave them (ADR 0011). */
export function prepareFrozenHelpCounts(
    article: string,
    named: readonly string[],
): FrozenHelpCounts {
    const { cached, text } = requireCachedArticleText(article);
    const cited = parseCitedHelpPhrases(Deno.readTextFileSync(REGISTER_PATH));
    if (cited.length === 0) {
        throw new HelpArticleError(`${REGISTER_PATH} cites no phrase, and freeze counts nothing`);
    }
    const counts = countPhrases(text, [...cited, ...named]);
    assert(counts.length > 0, "a table that is frozen counts something");
    const frozen = prepareFrozenFiles(
        [FROZEN_PATH],
        FROZEN_DATE_FIELD,
        cached.fetchedAt,
        counts.length,
        (date) => [encodeFrozenHelpModule(article, date, counts)],
    );
    return { ...frozen, counts };
}

/** Refuses rather than fetching behind the caller's back: a claim is dated by its dump. */
function requireCachedArticleText(article: string): { cached: CachedHelpArticle; text: string } {
    const cached = readCachedHelpArticle(article);
    if (cached === null) {
        throw new HelpArticleError(
            `nothing cached for article ${article} — run \`deno task margonem:help fetch\``,
        );
    }
    const text = Deno.readTextFileSync(cached.textPath);
    assert(text.length > 0, "a dump that was cached says something");
    return { cached, text };
}

/**
 * Counts, and deliberately nothing else: the help is the operator's own writing, and a count is
 * our measurement of the article rather than a piece of it (`NOTICE.md`). `fetchedAt` names the
 * first dump that gave these counts, not the day a person read it.
 */
export function encodeFrozenHelpModule(
    article: string,
    fetchedAt: string,
    counts: readonly [string, number][],
): string {
    const written = counts
        .map(([phrase, count]) => `        ${encodeRequiredText(phrase)}: ${formatInteger(count)},`)
        .join("\n");
    assert(written.length > 0, "a table that is written down says something");
    return `${FROZEN_HELP_BANNER}
export const FROZEN_HELP_PHRASES = {
    article: ${encodeRequiredText(article)},
    /** When the dump these counts were taken from was fetched, not when it was read. */
    ${FROZEN_DATE_FIELD}: ${encodeRequiredText(fetchedAt)},
    counts: {
${written}
    },
} as const;
`;
}

function encodeRequiredText(phrase: unknown): string {
    const text = encodeJson(phrase, 0);
    if (text instanceof Error) {
        throw new HelpArticleError("a phrase of the table cannot be written", {
            cause: text,
        });
    }
    return text;
}

/** What is cached for this article, or null. Absence is an answer; an unreadable file is not. */
export function readCachedHelpArticle(article: string): CachedHelpArticle | null {
    const text = errors.attempt(() => Deno.readTextFileSync(composeManifestPath(article)));
    if (text instanceof Error) {
        if (text.cause instanceof Deno.errors.NotFound) return null;
        throw new HelpArticleError(`cache manifest for ${article} cannot be read`, {
            cause: text,
        });
    }
    const parsed = parseJson(text);
    if (parsed instanceof Error) {
        throw new HelpArticleError(`cache manifest for ${article} is unreadable`, {
            cause: parsed,
        });
    }
    return requireCachedHelpArticle(parsed, article);
}

function composeManifestPath(article: string): string {
    const path = `${CACHE_ROOT}${article}/${MANIFEST_NAME}`;
    assert(path.startsWith(CACHE_ROOT), "a manifest sits under the cache nothing leaves");
    return path;
}

/** No `fetchedAt`, no age check: a field the manifest does not carry stops here (C13). */
export function requireCachedHelpArticle(manifest: unknown, article: string): CachedHelpArticle {
    if (!isRecord(manifest)) {
        throw new HelpArticleError(`cache manifest for ${article} is no object`);
    }
    if (manifest.article !== article) {
        throw new HelpArticleError(
            `cache manifest for ${article} says it holds ${manifest.article}`,
        );
    }
    const { url, fetchedAt, textPath, textLength } = manifest;
    if (typeof textLength !== "number") {
        throw new HelpArticleError(`cache manifest for ${article}: textLength is not a number`);
    }
    for (const [field, held] of [["url", url], ["fetchedAt", fetchedAt], ["textPath", textPath]]) {
        if (typeof held !== "string" || held.length === 0) {
            throw new HelpArticleError(`cache manifest for ${article}: ${field} is not stated`);
        }
    }
    assert(typeof url === "string", "the address was checked above");
    assert(typeof fetchedAt === "string", "and so was the date");
    assert(typeof textPath === "string", "and so was the path");
    return { article, url, fetchedAt, textPath, textLength };
}

/** How often each phrase occurs, deduplicated and sorted, so a re-freeze shows real change. */
export function countPhrases(text: string, phrases: readonly string[]): [string, number][] {
    const distinct = [...new Set(phrases)].sort();
    const counts = distinct.map((
        phrase,
    ): [string, number] => [phrase, countOccurrences(text, phrase)]);
    assert(counts.length <= phrases.length, "deduplication never invents a phrase");
    return counts;
}

export function countOccurrences(text: string, phrase: string): number {
    assert(phrase.length > 0, "an empty phrase is counted nowhere");
    return text.toLocaleLowerCase(LOCALE).split(phrase.toLocaleLowerCase(LOCALE)).length - 1;
}

/**
 * Slices around each hit, without repeating one already on screen. A repeat is recognised by the
 * slices **overlapping**, never by keying on a fragment's first characters: where the same content
 * precedes two hits, the keys collide and hits from different parts of the article vanish.
 */
export function lookupFragments(
    text: string,
    phrase: string,
    context: number,
    maximum: number,
): string[] {
    if (phrase === "") throw new HelpArticleError("an empty phrase matches everywhere");
    const needle = phrase.toLocaleLowerCase(LOCALE);
    const haystack = text.toLocaleLowerCase(LOCALE);
    const before = Math.round(context / 3);
    assert(before <= context, "the text in front of a hit is part of its window");
    assert(maximum >= 0, "a search shows no fewer fragments than none");
    const excerpts: string[] = [];
    let from = 0;
    let previousEnd = -1;
    // Each look moves past a hit of a phrase that is never empty, so one look per character ends it.
    for (let look = 0; look <= haystack.length; look += 1) {
        if (excerpts.length === maximum) return excerpts;
        const hit = haystack.indexOf(needle, from);
        if (hit === -1) return excerpts;
        from = hit + needle.length;
        if (hit < previousEnd) continue;
        const end = hit + context;
        excerpts.push(text.slice(Math.max(0, hit - before), end).trim());
        previousEnd = end;
    }
    throw new HelpArticleError(`the walk for "${phrase}" ran past the text it walks`);
}

/** Whether the dump is past the floor; an unreadable date counts as stale, being no date. */
export function isDumpStale(fetchedAt: string, now: number): boolean {
    const milliseconds = Date.parse(fetchedAt);
    if (!Number.isFinite(milliseconds)) return true;
    return Math.floor((now - milliseconds) / MILLISECONDS_PER_DAY) >= STALE_AFTER_DAYS;
}

/** How old the dump is, in words, and loudly once it is worth re-fetching. */
export function formatDumpAge(fetchedAt: string, now: number): string {
    const milliseconds = Date.parse(fetchedAt);
    if (!Number.isFinite(milliseconds)) return "read date unreadable — treat this dump as stale";
    // UTC spelled out: a file `ls` shows at 20:30 would otherwise read here as 18:30.
    const when = `${fetchedAt.slice(0, 16).split("T").join(" ")} UTC`;
    const days = Math.floor((now - milliseconds) / MILLISECONDS_PER_DAY);
    if (days <= 0) return `read ${when}, today`;
    if (days === 1) return `read ${when}, yesterday`;
    const warning = isDumpStale(fetchedAt, now) ? " ⚠ re-fetch before deciding" : "";
    return `read ${when}, ${formatInteger(days)} days ago${warning}`;
}

/** The article fetched, read as text and kept under `.cache/` beside the date it was fetched. */
export async function writeHelpArticleCache(article: string): Promise<CachedHelpArticle> {
    assert(parseInteger(article) !== null, "an article is asked for by its number");
    const url = `${HELP_HOST}/index/view,${article}`;
    const text = decodeHtmlText(await readMargonemAnswerText(url));
    const directory = `${CACHE_ROOT}${article}/`;
    Deno.mkdirSync(directory, { recursive: true });
    const textPath = `${directory}${TEXT_NAME}`;
    Deno.writeTextFileSync(textPath, text);
    const fetchedAt = new Date().toISOString();
    const cached = { article, url, fetchedAt, textPath, textLength: text.length };
    const written = encodeJson(cached, INDENT_SPACES);
    if (written instanceof Error) {
        throw new HelpArticleError(`provenance for ${article} cannot be written`, {
            cause: written,
        });
    }
    Deno.writeTextFileSync(composeManifestPath(article), `${written}\n`);
    return cached;
}

/** How many phrases found nothing, so silence is visible to a script and not only on screen. */
function writeHelpSearchReport(article: string, phrases: readonly string[]): number {
    const { cached, text } = requireCachedArticleText(article);
    const age = formatDumpAge(cached.fetchedAt, Date.now());
    console.log(`article view,${article} — ${formatInteger(text.length)} characters (${age})\n`);
    let missing = 0;
    for (const phrase of phrases) {
        const fragments = lookupFragments(text, phrase, CONTEXT_CHARACTERS, FRAGMENTS_SHOWN);
        const total = formatInteger(countOccurrences(text, phrase));
        console.log(`${"=".repeat(72)}\n"${phrase}" — ${total} occurrences\n${"=".repeat(72)}`);
        if (fragments.length === 0) {
            // Worded so it can go into a register unchanged: "not found" is not "not documented".
            console.log(`NOT FOUND in article view,${article}. Try the engine name — the help`);
            console.log(`prints it in parentheses beside the human one, as in "Unik ( evade )".`);
            missing += 1;
            continue;
        }
        for (const fragment of fragments) console.log(`\n… ${fragment} …`);
        console.log();
    }
    assert(missing <= phrases.length, "no more silences than phrases asked about");
    return missing;
}

if (import.meta.main) {
    const [command, ...phrases] = Deno.args;
    const article = MECHANICS_ARTICLE;
    if (command === "status") {
        const cached = readCachedHelpArticle(article);
        const said = cached === null
            ? "nothing cached"
            : `${formatInteger(cached.textLength)} characters  ${
                formatDumpAge(cached.fetchedAt, Date.now())
            }`;
        console.log(`view,${article}  ${said}`);
    } else if (command === "fetch") {
        const cached = await writeHelpArticleCache(article);
        const size = formatInteger(cached.textLength);
        console.log(`cached view,${cached.article} — ${size} characters → ${cached.textPath}`);
    } else if (command === "search") {
        if (phrases.length === 0) throw new HelpArticleError("search takes at least one phrase");
        // A non-zero exit is the point: a negative claim needs evidence as much as a positive one.
        if (writeHelpSearchReport(article, phrases) > 0) Deno.exitCode = 1;
    } else if (command === "freeze") {
        const { date, counts, hasMoved } = writeFrozenHelpCounts(article, phrases);
        const age = formatDumpAge(date, Date.now());
        const moved = hasMoved ? "froze" : "unchanged:";
        console.log(`${moved} ${formatInteger(counts.length)} phrases (${age}) → ${FROZEN_PATH}`);
        // A zero is the answer that gets written down as "not documented", so it is said aloud.
        const silent = counts.filter(([, found]) => found === 0).map(([phrase]) => phrase);
        if (silent.length > 0) console.log(`found nothing for: ${silent.join(", ")}`);
    } else {
        throw new HelpArticleError(
            "usage: deno task margonem:help status | fetch | search | freeze",
        );
    }
}
