/**
 * Every skill the game publishes, and the turns each of its effects is stated to run for. The
 * published table is the only source stating a duration: an effect reads `key=value@turns`, once
 * per skill level. Ids, effect keys and turns are kept; the description column is the game's own
 * prose and stays in the cache (`SECURITY.md`, `NOTICE.md`). Which effects reach a side is
 * `src/core/aura-standing.ts`'s to say, and this asks it.
 *
 *     deno task game:skills status | fetch | freeze
 */

import { assert, assertStrictEquals } from "@std/assert";
import { decodeHtmlText } from "#/libs/html-text.ts";
import { encodeJson, parseJson } from "#/libs/json-text.ts";
import { formatInteger, parseInteger } from "#/libs/number-text.ts";
import * as errors from "#/libs/errors.ts";
import { isRecord } from "#/libs/unknown-value.ts";
import {
    indexAuraTurnsBySkillId,
    lookupStatedTurns,
    type SkillEffectTurns,
} from "#/src/core/aura-standing.ts";
import { PROVOCATION_KEY } from "#/src/core/protocol-key.ts";
import { GameUnreachableError, SkillTableError } from "./margometer-tool-error.ts";

export interface CachedSkillTable {
    url: string;
    fetchedAt: string;
    pagePath: string;
    pageLength: number;
}

/** One effect as the table states it, level by level, with the figures only this tool reads. */
export interface SkillEffectReading extends SkillEffectTurns {
    /** The value in front of the `@` at each level, where the level states one. */
    amounts: readonly number[];
    /** The value at each level, whether or not a duration stands beside it. */
    values: readonly number[];
}

export interface SkillReading {
    id: number;
    effects: readonly SkillEffectReading[];
}

const SKILLS_ADDRESS = "https://public-api.margonem.pl/we_get/skills/";
/** Ignored by git, and exported for the reason `tools/game-client-source.ts` gives for its own. */
export const CACHE_ROOT = ".cache/skills/";
const MANIFEST_NAME = "provenance.json";
const PAGE_NAME = "skills.html";
export const FROZEN_PATH = "frozen/skill-durations.ts";
export const FROZEN_AURA_PATH = "frozen/aura-turns.ts";
export const FROZEN_BLOWS_PATH = "frozen/blows-granted.ts";
const ROW_OPEN = "<tr>";
const CELL_OPEN = "<td>";
const CELL_CLOSE = "</td>";
/**
 * The columns the page serves, in its order. Two are read; the rest are named so a page gaining
 * or losing one is refused rather than read off by one, which would freeze a description where the
 * effects were.
 */
const COLUMNS = ["id", "tags", "name", "description", "profession", "levels", "effects", "needs"];
const IDENTITY_COLUMN = 0;
const EFFECTS_COLUMN = 6;
const EFFECT_TERMINATOR = ";";
const EFFECT_ASSIGNMENT = "=";
const LEVEL_SEPARATOR = ",";
const DURATION_MARKER = "@";
/** The effect naming attacks a skill grants beyond its own: the game's word, spelled once (N13). */
export const BLOWS_GRANTED_KEY = "add_attacks";
/** Past the row, cell and effect counts the page has ever served, so each walk is bounded. */
const ROWS_MAXIMUM = 4096;
const CELLS_MAXIMUM = 64;
const EFFECTS_MAXIMUM = 64;
const INDENT_SPACES = 2;
export const FROZEN_SKILL_BANNER =
    "// Generated by `deno task game:skills freeze`. Do not edit by hand.\n//\n" +
    "// Ids, effect keys and stated turns only, and `tools/skill-table.ts` says why the\n" +
    "// description column the page serves beside them stays in the cache.\n";
/** Why the date is the page's and not the reader's, said in the file a reader opens. */
const DATE_NOTE =
    "    /** When the page these were read from was fetched, not when a person read it. */";
const FROZEN_BLOWS_BANNER =
    "// Generated by `deno task game:skills freeze`. Do not edit by hand.\n//\n" +
    "// The skills the published table grants an attack beyond their own, and the fewest it\n" +
    "// grants at any level. `src/core/fight-decoder.ts` is what reads them: an announcement\n" +
    "// reaches one blow further for each.\n";
const FROZEN_AURA_BANNER =
    "// Generated by `deno task game:skills freeze`. Do not edit by hand.\n//\n" +
    "// The skills whose effects reach more than one combatant, and the turns the published\n" +
    "// table states each runs for. `src/core/aura-standing.ts` owns which keys those are.\n" +
    "//\n// A shout states a count of characters where the others state a share, so it is\n" +
    "// frozen apart: its own turns, and the fewest it covers at any level.\n";

/** The three frozen readings, written off one cached page so they date together. */
export function writeFrozenSkillTable(): {
    fetchedAt: string;
    skills: number;
    auras: number;
    granted: number;
} {
    const { cached, skills } = requireCachedSkills();
    const auras = composeAuraSkills(skills);
    const shouts = composeShoutSkills(skills);
    const granted = composeGrantedBlows(skills);
    const dated = `${DATE_NOTE}\n    fetchedAt: ${JSON.stringify(cached.fetchedAt)},\n`;
    Deno.writeTextFileSync(
        FROZEN_PATH,
        `${FROZEN_SKILL_BANNER}\nexport const FROZEN_SKILL_DURATIONS = {\n${dated}` +
            `    skills: [\n${encodeFrozenSkills(skills)}\n    ],\n} as const;\n`,
    );
    const rows = auras.map((one) =>
        `        { id: ${formatInteger(one.id)}, turns: ${one.turns} },`
    );
    const shouted = shouts.map((one) =>
        `        { id: ${formatInteger(one.id)}, turns: ${one.turns}, ` +
        `coverageMinimum: ${one.coverageMinimum} },`
    );
    Deno.writeTextFileSync(
        FROZEN_AURA_PATH,
        `${FROZEN_AURA_BANNER}\nexport const FROZEN_AURA_TURNS = {\n${dated}    skills: [\n` +
            `${rows.join("\n")}\n    ],\n    shouts: [\n${
                shouted.join("\n")
            }\n    ],\n} as const;\n`,
    );
    const blows = granted.map((one) =>
        `        { id: ${formatInteger(one.id)}, blowsGrantedMinimum: ${one.blowsGrantedMinimum} },`
    );
    Deno.writeTextFileSync(
        FROZEN_BLOWS_PATH,
        `${FROZEN_BLOWS_BANNER}\nexport const FROZEN_BLOWS_GRANTED = {\n${dated}` +
            `    skills: [\n${blows.join("\n")}\n    ],\n} as const;\n`,
    );
    assert(shouts.length <= auras.length, "a shout reaches a side, so it is among them");
    return {
        fetchedAt: cached.fetchedAt,
        skills: skills.length,
        auras: auras.length,
        granted: granted.length,
    };
}

/** The page as it was cached, refused rather than guessed at where nothing is. */
function requireCachedSkills(): { cached: CachedSkillTable; skills: SkillReading[] } {
    const cached = readCachedSkillTable();
    if (cached === null) {
        throw new SkillTableError("nothing cached — run `deno task game:skills fetch` first");
    }
    const html = Deno.readTextFileSync(cached.pagePath);
    assert(html.length > 0, "a cached page says something");
    return { cached, skills: requireSkillsOfPage(html) };
}

/**
 * One effect to a line, whatever a skill states. A generated file the formatter would rewrite
 * fails the gate the run after it is generated, so the shape written is the one `deno fmt` keeps.
 */
function encodeFrozenSkills(skills: readonly SkillReading[]): string {
    const lines: string[] = [];
    for (const skill of skills) {
        lines.push(
            `        {`,
            `            id: ${formatInteger(skill.id)},`,
            `            effects: [`,
        );
        for (const effect of skill.effects) {
            const turns = effect.turns.map((one) => formatInteger(one)).join(", ");
            lines.push(
                `                { key: ${JSON.stringify(effect.key)}, turns: [${turns}] },`,
            );
        }
        lines.push(`            ],`, `        },`);
    }
    assert(skills.length > 0, "a frozen reading holds the skills the page served");
    return lines.join("\n");
}

/** Null where nothing is cached, which is a state and not a failure. */
export function readCachedSkillTable(): CachedSkillTable | null {
    const text = errors.attempt(() => Deno.readTextFileSync(`${CACHE_ROOT}${MANIFEST_NAME}`));
    if (text instanceof Error) return null;
    const parsed = parseJson(text);
    if (parsed instanceof Error) throw new SkillTableError("the skill manifest is not JSON");
    return requireCachedSkillTable(parsed);
}

function requireCachedSkillTable(value: unknown): CachedSkillTable {
    if (!isRecord(value)) throw new SkillTableError("the skill cache states no manifest");
    const { url, fetchedAt, pagePath, pageLength } = value;
    if (typeof url !== "string") throw new SkillTableError("the skill cache names no address");
    if (typeof fetchedAt !== "string") throw new SkillTableError("the skill cache has no date");
    if (typeof pagePath !== "string") throw new SkillTableError("the skill cache names no page");
    if (typeof pageLength !== "number") throw new SkillTableError("the cache states no length");
    assert(fetchedAt.length > 0, "a cached reading carries the date it was taken on");
    return { url, fetchedAt, pagePath, pageLength };
}

/** Rows carrying exactly the columns named above; a page of another shape is refused. */
export function requireSkillsOfPage(html: string): SkillReading[] {
    const found: SkillReading[] = [];
    const rows = html.split(ROW_OPEN);
    assert(rows.length <= ROWS_MAXIMUM, "the page stays inside its stated bound");
    for (const row of rows.slice(1)) {
        const cells = parseRowCells(row);
        if (cells.length !== COLUMNS.length) continue;
        const id = parseInteger((cells[IDENTITY_COLUMN] ?? "").trim());
        if (id === null) continue;
        found.push({ id, effects: parseCellEffects(cells[EFFECTS_COLUMN] ?? "") });
    }
    if (found.length === 0) {
        throw new SkillTableError(
            `the skill table served no row of ${formatInteger(COLUMNS.length)} columns`,
        );
    }
    assertStrictEquals(new Set(found.map((one) => one.id)).size, found.length, "a skill once");
    return found;
}

/** The cells of one row, as the text a person would have seen in each. */
function parseRowCells(row: string): string[] {
    const cells: string[] = [];
    let from = 0;
    for (let look = 0; look < CELLS_MAXIMUM; look += 1) {
        const open = row.indexOf(CELL_OPEN, from);
        if (open === -1) break;
        const close = row.indexOf(CELL_CLOSE, open + CELL_OPEN.length);
        if (close === -1) break;
        cells.push(decodeHtmlText(row.slice(open + CELL_OPEN.length, close)));
        from = close + CELL_CLOSE.length;
    }
    return cells;
}

function parseCellEffects(cell: string): SkillEffectReading[] {
    const found: SkillEffectReading[] = [];
    for (const stated of cell.split(EFFECT_TERMINATOR)) {
        assert(found.length <= EFFECTS_MAXIMUM, "a skill stays inside its stated bound");
        const effect = parseEffect(stated.trim());
        if (effect !== null) found.push(effect);
    }
    return found;
}

/**
 * `key=value@turns,value@turns`: the turns each level states, and none where it states none.
 * ⚠️ **A level states a value whether or not a duration stands beside it.** `add_attacks=1` has no
 * `@` at all, so a walk skipping such a level would throw away the only figure it carries.
 */
export function parseEffect(text: string): SkillEffectReading | null {
    const at = text.indexOf(EFFECT_ASSIGNMENT);
    if (at <= 0) return null;
    const key = text.slice(0, at).trim();
    if (key.length === 0) return null;
    const turns: number[] = [];
    const amounts: number[] = [];
    const values: number[] = [];
    for (const level of text.slice(at + 1).split(LEVEL_SEPARATOR)) {
        const marked = level.indexOf(DURATION_MARKER);
        const value = parseInteger((marked === -1 ? level : level.slice(0, marked)).trim());
        if (value !== null) values.push(value);
        if (marked === -1) continue;
        const stated = parseInteger(level.slice(marked + 1).trim());
        if (stated === null) continue;
        turns.push(stated);
        if (value !== null) amounts.push(value);
    }
    assert(amounts.length <= turns.length, "an amount is read only beside a duration");
    return { key, turns, amounts, values };
}

/** The small table the bundle carries: the skills reaching a side, and nothing else. */
export function composeAuraSkills(
    skills: readonly SkillReading[],
): { id: number; turns: number }[] {
    const found: { id: number; turns: number }[] = [];
    for (const skill of skills) {
        const turns = lookupStatedTurns(skill.effects);
        if (turns !== null) found.push({ id: skill.id, turns });
    }
    assertStrictEquals(indexAuraTurnsBySkillId(found).size, found.length, "each is named once");
    return found;
}

/**
 * A shout's value in front of the `@` is a count of characters rather than a share. The turns are
 * the longest stated; the coverage the fewest, because the panel does not know the caster's level
 * and may only rely on what holds at every one. Measured 2026-09-08: both skills state 3 turns at
 * all ten levels, and a coverage rising from 6 to 10.
 */
export function composeShoutSkills(
    skills: readonly SkillReading[],
): { id: number; turns: number; coverageMinimum: number }[] {
    const found: { id: number; turns: number; coverageMinimum: number }[] = [];
    for (const skill of skills) {
        const shout = skill.effects.find((one) => one.key === PROVOCATION_KEY);
        if (shout === undefined) continue;
        if (shout.turns.length === 0) continue;
        if (shout.amounts.length === 0) continue;
        const turns = Math.max(...shout.turns);
        found.push({ id: skill.id, turns, coverageMinimum: Math.min(...shout.amounts) });
    }
    assert(found.every((one) => one.coverageMinimum > 0), "a shout covers somebody");
    return found;
}

/**
 * What the table grants beyond a skill's own attack: the fewest at any level, for the reason a
 * shout's coverage is. Measured 2026-09-12: three of 226 skills state it, one value each.
 */
export function composeGrantedBlows(
    skills: readonly SkillReading[],
): { id: number; blowsGrantedMinimum: number }[] {
    const found: { id: number; blowsGrantedMinimum: number }[] = [];
    for (const skill of skills) {
        const granted = skill.effects.find((one) => one.key === BLOWS_GRANTED_KEY);
        if (granted === undefined) continue;
        if (granted.values.length === 0) continue;
        found.push({ id: skill.id, blowsGrantedMinimum: Math.min(...granted.values) });
    }
    assert(found.every((one) => one.blowsGrantedMinimum > 0), "a grant is worth a blow");
    return found;
}

/** The page fetched and kept under `.cache/`, beside the date it was fetched on. */
export async function writeSkillTableCache(): Promise<CachedSkillTable> {
    let response: Response;
    // The network, which is `tools/`'s own boundary (E5).
    try {
        response = await fetch(SKILLS_ADDRESS);
    } catch (cause) {
        throw new GameUnreachableError(`${SKILLS_ADDRESS} did not answer`, { cause });
    }
    if (!response.ok) {
        throw new GameUnreachableError(`${SKILLS_ADDRESS} answered ${response.status}`);
    }
    const html = await response.text();
    const pagePath = `${CACHE_ROOT}${PAGE_NAME}`;
    Deno.mkdirSync(CACHE_ROOT, { recursive: true });
    Deno.writeTextFileSync(pagePath, html);
    const fetchedAt = new Date().toISOString();
    const cached = { url: SKILLS_ADDRESS, fetchedAt, pagePath, pageLength: html.length };
    const written = encodeJson(cached, INDENT_SPACES);
    if (written instanceof Error) {
        throw new SkillTableError("the skill manifest could not be written");
    }
    Deno.writeTextFileSync(`${CACHE_ROOT}${MANIFEST_NAME}`, `${written}\n`);
    assert(html.length > 0, "a page that was fetched says something");
    return cached;
}

if (import.meta.main) {
    const [command] = Deno.args;
    if (command === "status") {
        const cached = readCachedSkillTable();
        if (cached === null) console.log("skill table   nothing cached");
        else {
            const count = formatInteger(requireCachedSkills().skills.length);
            console.log(`skill table   cached ${cached.fetchedAt}  ${count} skills`);
        }
    } else if (command === "fetch") {
        const cached = await writeSkillTableCache();
        const length = formatInteger(cached.pageLength);
        console.log(`cached ${cached.url} — ${length} characters → ${cached.pagePath}`);
    } else if (command === "freeze") {
        const frozen = writeFrozenSkillTable();
        console.log(
            `froze ${formatInteger(frozen.skills)} skills → ${FROZEN_PATH}, ` +
                `${formatInteger(frozen.auras)} reaching a side → ${FROZEN_AURA_PATH}, and ` +
                `${formatInteger(frozen.granted)} granting a blow → ${FROZEN_BLOWS_PATH}`,
        );
    } else {
        throw new SkillTableError(`unknown command "${command ?? ""}" — status, fetch or freeze`);
    }
}
