/**
 * Every skill the game publishes, and the turns each of its effects is stated to run for. The
 * published table is the only source stating a duration: an effect reads `key=value@turns`, once
 * per skill level. Ids, effect keys and turns are kept; the description column is the game's own
 * prose and stays in the cache (`SECURITY.md`, `NOTICE.md`). Which effects reach a side is
 * `src/core/aura-standing.ts`'s to say, and this asks it.
 *
 *     deno task margonem:skills status | fetch | freeze
 */

import { assert, assertStrictEquals } from "@std/assert";
import { decodeHtmlText, HTML_CHARACTERS_MAXIMUM } from "#/libs/html-text.ts";
import { encodeJson, parseJson } from "#/libs/json-text.ts";
import { formatInteger, parseInteger } from "#/libs/number-text.ts";
import * as errors from "#/libs/errors.ts";
import { isRecord } from "#/libs/unknown-value.ts";
import {
    indexAuraTurnsBySkillId,
    lookupAuraTurnsStated,
    SKILL_EFFECTS_MAXIMUM,
    type SkillEffectTurns,
    SKILLS_DATED_MAXIMUM,
} from "#/src/core/aura-standing.ts";
import { BLOWS_GRANTED_MAXIMUM } from "#/src/core/fight-decoder.ts";
import { PROVOCATION_KEY } from "#/src/core/protocol-key.ts";
import { type FrozenFiles, readFrozenFiles, writeFrozenFiles } from "./frozen-files.ts";
import { readMargonemAnswerText } from "./margonem-client-source.ts";
import { SkillTableError } from "./margometer-tool-error.ts";

export interface CachedSkillTable {
    url: string;
    fetchedAt: string;
    pagePath: string;
    pageLength: number;
}

/** One effect as the table states it, level by level, with the figures only this tool reads. */
export interface SkillEffectReading extends SkillEffectTurns {
    /** The value in front of the `@` at each level, where the level states one. */
    amounts: readonly number[];
    /** The value at each level, whether or not a duration stands beside it. */
    values: readonly number[];
}

export interface SkillReading {
    id: number;
    effects: readonly SkillEffectReading[];
}

export interface AuraSkill {
    id: number;
    turns: number;
}

export interface ShoutSkill extends AuraSkill {
    coverageMinimum: number;
}

export interface GrantedBlows {
    id: number;
    blowsGrantedMinimum: number;
}

/** A freeze of the three readings, with what the two smaller ones count. */
export interface FrozenSkillTable extends FrozenFiles {
    auras: number;
    granted: number;
}

const SKILLS_ADDRESS = "https://public-api.margonem.pl/we_get/skills/";
/** Ignored by git, and exported for the reason `tools/margonem-client-source.ts` gives for its own. */
export const CACHE_ROOT = ".cache/skills/";
const MANIFEST_NAME = "provenance.json";
const PAGE_NAME = "skills.html";
export const FROZEN_PATH = "frozen/skill-durations.ts";
export const FROZEN_AURA_PATH = "frozen/aura-turns.ts";
export const FROZEN_BLOWS_PATH = "frozen/blows-granted.ts";
/** The field the reading is dated by, exported so a test holds the frozen file to it. */
export const FROZEN_DATE_FIELD = "fetchedAt";
const ROW_OPEN = "<tr>";
const CELL_OPEN = "<td>";
const CELL_CLOSE = "</td>";
/**
 * The columns the page serves, in its order. Two are read; the rest are named so a page gaining
 * or losing one is refused rather than read off by one, which would freeze a description where the
 * effects were.
 */
const COLUMNS = [
    "id",
    "tags",
    "name",
    "description",
    "profession",
    "levels",
    "effects",
    "needs",
] as const;
const IDENTITY_COLUMN = COLUMNS.indexOf("id");
const EFFECTS_COLUMN = COLUMNS.indexOf("effects");
const EFFECT_TERMINATOR = ";";
const EFFECT_ASSIGNMENT = "=";
const LEVEL_SEPARATOR = ",";
const DURATION_MARKER = "@";
/** The effect naming attacks a skill grants beyond its own: the game's word, spelled once (N13). */
export const BLOWS_GRANTED_KEY = "add_attacks";
/** Past the row, cell and effect counts the page has ever served, so each walk is bounded. */
export const ROWS_MAXIMUM = 4096;
const CELLS_MAXIMUM = 64;
/** What the add-on reads of one skill's effects, so a page past it is refused before it is frozen. */
export const EFFECTS_MAXIMUM = SKILL_EFFECTS_MAXIMUM;
const INDENT_SPACES = 2;
const FROZEN_SKILL_BANNER =
    "// Generated by `deno task margonem:skills freeze`. Do not edit by hand.\n//\n" +
    "// Ids, effect keys and stated turns only, and `tools/skill-table.ts` says why the\n" +
    "// description column the page serves beside them stays in the cache.\n";
/** Why the date is the page's and not the reader's, said in the file a reader opens. */
const DATE_NOTE =
    "    /** When the page these were read from was fetched, not when a person read it. */";
const FROZEN_BLOWS_BANNER =
    "// Generated by `deno task margonem:skills freeze`. Do not edit by hand.\n//\n" +
    "// The skills the published table grants an attack beyond their own, and the fewest it\n" +
    "// grants at any level. `src/core/fight-decoder.ts` is what reads them: an announcement\n" +
    "// reaches one blow further for each.\n";
const FROZEN_AURA_BANNER =
    "// Generated by `deno task margonem:skills freeze`. Do not edit by hand.\n//\n" +
    "// The skills whose effects reach more than one combatant, and the turns the published\n" +
    "// table states each runs for. `src/core/aura-standing.ts` owns which keys those are.\n" +
    "//\n// A shout states a count of characters where the others state a share, so it is\n" +
    "// frozen apart: its own turns, and the fewest it covers at any level.\n";

/** The three frozen readings, written where they moved. */
export function writeFrozenSkillTable(): FrozenSkillTable {
    const frozen = readFrozenSkillTable();
    writeFrozenFiles(frozen);
    return frozen;
}

/**
 * The three readings off one cached page, dated by the first page that gave all three (ADR 0011):
 * one of them moving re-dates the others, because they date together.
 */
export function readFrozenSkillTable(): FrozenSkillTable {
    const { cached, skills } = readCachedSkills();
    const auras = composeAuraSkills(skills);
    const shouts = composeShoutSkills(skills);
    const granted = composeGrantedBlows(skills);
    const frozen = readFrozenFiles(
        [FROZEN_PATH, FROZEN_AURA_PATH, FROZEN_BLOWS_PATH],
        FROZEN_DATE_FIELD,
        cached.fetchedAt,
        skills.length,
        (date) => encodeFrozenSkillTexts(date, skills, auras, shouts, granted),
    );
    return { ...frozen, auras: auras.length, granted: granted.length };
}

/** The page as it was cached, refused rather than guessed at where nothing is. */
function readCachedSkills(): { cached: CachedSkillTable; skills: SkillReading[] } {
    const cached = readCachedSkillTable();
    if (cached === null) {
        throw new SkillTableError("nothing cached — run `deno task margonem:skills fetch` first");
    }
    const html = errors.attempt(() => Deno.readTextFileSync(cached.pagePath));
    if (html instanceof Error) {
        throw new SkillTableError(
            `${cached.pagePath} cannot be read — run \`deno task margonem:skills fetch\``,
            { cause: html },
        );
    }
    assert(html.length > 0, "a cached page says something");
    return { cached, skills: requireSkillsOfMargonemApi(html) };
}

export function encodeFrozenSkillTexts(
    date: string,
    skills: readonly SkillReading[],
    auras: readonly AuraSkill[],
    shouts: readonly ShoutSkill[],
    granted: readonly GrantedBlows[],
): string[] {
    assert(date.length > 0, "a reading is dated");
    const dated = `${DATE_NOTE}\n    ${FROZEN_DATE_FIELD}: ${JSON.stringify(date)},\n`;
    const durations = `${FROZEN_SKILL_BANNER}\nexport const FROZEN_SKILL_DURATIONS = {\n${dated}` +
        `    skills: [\n${encodeFrozenSkills(skills)}\n    ],\n} as const;\n`;
    const rows = auras.map((aura) =>
        `        { id: ${formatInteger(aura.id)}, turns: ${aura.turns} },`
    );
    const shouted = shouts.map((shout) =>
        `        { id: ${formatInteger(shout.id)}, turns: ${shout.turns}, ` +
        `coverageMinimum: ${shout.coverageMinimum} },`
    );
    const aurasText = `${FROZEN_AURA_BANNER}\nexport const FROZEN_AURA_TURNS = {\n${dated}` +
        `    skills: [\n${rows.join("\n")}\n    ],\n    shouts: [\n${
            shouted.join("\n")
        }\n    ],\n} as const;\n`;
    const blows = granted.map((grant) =>
        `        { id: ${
            formatInteger(grant.id)
        }, blowsGrantedMinimum: ${grant.blowsGrantedMinimum} },`
    );
    const blowsText = `${FROZEN_BLOWS_BANNER}\nexport const FROZEN_BLOWS_GRANTED = {\n${dated}` +
        `    skills: [\n${blows.join("\n")}\n    ],\n} as const;\n`;
    return [durations, aurasText, blowsText];
}

/**
 * One effect to a line, whatever a skill states. A generated file the formatter would rewrite
 * fails the gate the run after it is generated, so the shape written is the one `deno fmt` keeps.
 */
function encodeFrozenSkills(skills: readonly SkillReading[]): string {
    const lines: string[] = [];
    for (const skill of skills) {
        lines.push(
            `        {`,
            `            id: ${formatInteger(skill.id)},`,
            `            effects: [`,
        );
        for (const effect of skill.effects) {
            const turns = effect.turns.map((levelTurns) => formatInteger(levelTurns)).join(", ");
            lines.push(
                `                { key: ${JSON.stringify(effect.key)}, turns: [${turns}] },`,
            );
        }
        lines.push(`            ],`, `        },`);
    }
    assert(skills.length > 0, "a frozen reading holds the skills the page served");
    return lines.join("\n");
}

/** Null where nothing is cached, which is a state and not a failure. */
export function readCachedSkillTable(): CachedSkillTable | null {
    const text = errors.attempt(() => Deno.readTextFileSync(`${CACHE_ROOT}${MANIFEST_NAME}`));
    if (text instanceof Error) {
        if (text.cause instanceof Deno.errors.NotFound) return null;
        throw new SkillTableError("the skill manifest cannot be read", { cause: text });
    }
    const parsed = parseJson(text);
    if (parsed instanceof Error) {
        throw new SkillTableError("the skill manifest is not JSON", { cause: parsed });
    }
    return requireCachedSkillTable(parsed);
}

function requireCachedSkillTable(manifest: unknown): CachedSkillTable {
    if (!isRecord(manifest)) throw new SkillTableError("the skill cache states no manifest");
    const { url, fetchedAt, pagePath, pageLength } = manifest;
    if (typeof url !== "string") throw new SkillTableError("the skill cache names no address");
    if (typeof fetchedAt !== "string") throw new SkillTableError("the skill cache has no date");
    if (typeof pagePath !== "string") throw new SkillTableError("the skill cache names no page");
    if (typeof pageLength !== "number") throw new SkillTableError("the cache states no length");
    assert(fetchedAt.length > 0, "a cached reading carries the date it was taken on");
    return { url, fetchedAt, pagePath, pageLength };
}

/** Rows carrying exactly the columns named above; a page of another shape is refused. */
export function requireSkillsOfMargonemApi(html: string): SkillReading[] {
    requirePageInsideBound(html);
    const skills: SkillReading[] = [];
    // What stands before the first row is the page around the table, and no row.
    const rows = html.split(ROW_OPEN).slice(1);
    if (rows.length > ROWS_MAXIMUM) {
        throw new SkillTableError(`the skill table serves more than ${ROWS_MAXIMUM} rows`);
    }
    for (const row of rows) {
        const cells = parseRowCells(row);
        if (cells.length === 0) continue;
        if (cells.length !== COLUMNS.length) {
            throw new SkillTableError(
                `a row of ${formatInteger(cells.length)} columns where the table serves ${
                    formatInteger(COLUMNS.length)
                }`,
            );
        }
        const id = parseInteger((cells[IDENTITY_COLUMN] ?? "").trim());
        // The page served 226 rows and 226 ids on 2026-10-06, no heading among them: a row that
        // states none is a page that changed, and passing it over would freeze a table short of it.
        if (id === null) {
            throw new SkillTableError(
                `row ${formatInteger(skills.length + 1)} states no id where the table serves one`,
            );
        }
        skills.push({ id, effects: parseCellEffects(cells[EFFECTS_COLUMN] ?? "") });
    }
    if (skills.length === 0) {
        throw new SkillTableError(
            `the skill table served no row of ${formatInteger(COLUMNS.length)} columns`,
        );
    }
    assertStrictEquals(
        new Set(skills.map((skill) => skill.id)).size,
        skills.length,
        "a skill once",
    );
    return skills;
}

/** A page past the length one is walked to, refused before a row of it is read. */
function requirePageInsideBound(html: string): void {
    if (html.length <= HTML_CHARACTERS_MAXIMUM) return;
    throw new SkillTableError(
        `the skill table is ${formatInteger(html.length)} characters, past the ${
            formatInteger(HTML_CHARACTERS_MAXIMUM)
        } a page is read to`,
    );
}

/** The cells of one row, as the text a person would have seen in each. */
function parseRowCells(row: string): string[] {
    const cells: string[] = [];
    let from = 0;
    for (let look = 0; look < CELLS_MAXIMUM; look += 1) {
        const open = row.indexOf(CELL_OPEN, from);
        if (open === -1) break;
        const close = row.indexOf(CELL_CLOSE, open + CELL_OPEN.length);
        if (close === -1) break;
        cells.push(decodeHtmlText(row.slice(open + CELL_OPEN.length, close)));
        from = close + CELL_CLOSE.length;
    }
    return cells;
}

function parseCellEffects(cell: string): SkillEffectReading[] {
    const effects: SkillEffectReading[] = [];
    for (const stated of cell.split(EFFECT_TERMINATOR)) {
        const effect = parseEffect(stated.trim());
        if (effect === null) continue;
        if (effects.length === EFFECTS_MAXIMUM) {
            throw new SkillTableError(`a skill states more than ${EFFECTS_MAXIMUM} effects`);
        }
        effects.push(effect);
    }
    assert(effects.length <= EFFECTS_MAXIMUM, "a skill stays inside its stated bound");
    return effects;
}

/**
 * `key=value@turns,value@turns`: the turns each level states, and none where it states none.
 * ⚠️ **A level states a value whether or not a duration stands beside it.** `add_attacks=1` has no
 * `@` at all, so a walk skipping such a level would throw away the only figure it carries.
 */
function parseEffect(text: string): SkillEffectReading | null {
    const assignmentAt = text.indexOf(EFFECT_ASSIGNMENT);
    if (assignmentAt <= 0) return null;
    const key = text.slice(0, assignmentAt).trim();
    if (key.length === 0) return null;
    const turns: number[] = [];
    const amounts: number[] = [];
    const values: number[] = [];
    for (const level of text.slice(assignmentAt + 1).split(LEVEL_SEPARATOR)) {
        const marked = level.indexOf(DURATION_MARKER);
        const levelValue = parseInteger((marked === -1 ? level : level.slice(0, marked)).trim());
        if (levelValue !== null) values.push(levelValue);
        if (marked === -1) continue;
        const stated = parseInteger(level.slice(marked + 1).trim());
        if (stated === null) continue;
        turns.push(stated);
        if (levelValue !== null) amounts.push(levelValue);
    }
    assert(amounts.length <= turns.length, "an amount is read only beside a duration");
    return { key, turns, amounts, values };
}

/** The small table the bundle carries: the skills reaching a side, and nothing else. */
export function composeAuraSkills(
    skills: readonly SkillReading[],
): AuraSkill[] {
    const auraSkills: AuraSkill[] = [];
    for (const skill of skills) {
        const turns = lookupAuraTurnsStated(skill.effects);
        if (turns !== null) auraSkills.push({ id: skill.id, turns });
    }
    if (auraSkills.length > SKILLS_DATED_MAXIMUM) {
        throw new SkillTableError(
            `more than ${SKILLS_DATED_MAXIMUM} skills reach a side, past what the add-on dates`,
        );
    }
    assertStrictEquals(
        indexAuraTurnsBySkillId(auraSkills).size,
        auraSkills.length,
        "each is named once",
    );
    return auraSkills;
}

/**
 * A shout's value in front of the `@` is a count of characters rather than a share. The turns are
 * the longest stated; the coverage the fewest, because the panel does not know the caster's level
 * and may only rely on what holds at every one. What the page comes to is `shouts` in
 * `frozen/aura-turns.ts`.
 */
export function composeShoutSkills(
    skills: readonly SkillReading[],
): ShoutSkill[] {
    const shoutSkills: ShoutSkill[] = [];
    for (const skill of skills) {
        const shout = skill.effects.find((effect) => effect.key === PROVOCATION_KEY);
        if (shout === undefined) continue;
        if (shout.turns.length === 0) continue;
        if (shout.amounts.length === 0) continue;
        const turns = Math.max(...shout.turns);
        const coverageMinimum = Math.min(...shout.amounts);
        // The add-on asserts a shout holds a while and somebody, so a page saying less is refused.
        if (turns <= 0) {
            throw new SkillTableError(`skill ${skill.id} states a shout holding for no turn`);
        }
        if (coverageMinimum <= 0) {
            throw new SkillTableError(`skill ${skill.id} states a shout covering nobody`);
        }
        shoutSkills.push({ id: skill.id, turns, coverageMinimum });
    }
    return shoutSkills;
}

/**
 * What the table grants beyond a skill's own attack: the fewest at any level, for the reason a
 * shout's coverage is. The skills stating it are `frozen/blows-granted.ts`.
 */
export function composeGrantedBlows(
    skills: readonly SkillReading[],
): GrantedBlows[] {
    const grantedBlows: GrantedBlows[] = [];
    for (const skill of skills) {
        const granted = skill.effects.find((effect) => effect.key === BLOWS_GRANTED_KEY);
        if (granted === undefined) continue;
        if (granted.values.length === 0) continue;
        const blowsGrantedMinimum = Math.min(...granted.values);
        // The add-on asserts a grant inside its own reach, so a page past it is refused here.
        if (blowsGrantedMinimum <= 0) {
            throw new SkillTableError(`skill ${skill.id} states a grant of no blow`);
        }
        if (blowsGrantedMinimum >= BLOWS_GRANTED_MAXIMUM) {
            throw new SkillTableError(
                `skill ${skill.id} grants ${blowsGrantedMinimum} blows, past the ` +
                    `${BLOWS_GRANTED_MAXIMUM - 1} an announcement reaches`,
            );
        }
        grantedBlows.push({ id: skill.id, blowsGrantedMinimum });
    }
    return grantedBlows;
}

/** The page fetched and kept under `.cache/`, beside the date it was fetched on. */
export async function writeSkillTableCache(): Promise<CachedSkillTable> {
    const html = await readMargonemAnswerText(SKILLS_ADDRESS);
    // Checked before anything is written: an empty answer written over a good cache leaves every
    // later freeze with nothing to read.
    if (html.length === 0) throw new SkillTableError(`${SKILLS_ADDRESS} answered nothing`);
    requirePageInsideBound(html);
    const pagePath = `${CACHE_ROOT}${PAGE_NAME}`;
    Deno.mkdirSync(CACHE_ROOT, { recursive: true });
    Deno.writeTextFileSync(pagePath, html);
    const fetchedAt = new Date().toISOString();
    const cached = { url: SKILLS_ADDRESS, fetchedAt, pagePath, pageLength: html.length };
    const written = encodeJson(cached, INDENT_SPACES);
    if (written instanceof Error) {
        throw new SkillTableError("the skill manifest could not be written", { cause: written });
    }
    Deno.writeTextFileSync(`${CACHE_ROOT}${MANIFEST_NAME}`, `${written}\n`);
    return cached;
}

if (import.meta.main) {
    const [command] = Deno.args;
    if (command === "status") {
        const cached = readCachedSkillTable();
        if (cached === null) console.log("skill table   nothing cached");
        else {
            const count = formatInteger(readCachedSkills().skills.length);
            console.log(`skill table   cached ${cached.fetchedAt}  ${count} skills`);
        }
    } else if (command === "fetch") {
        const cached = await writeSkillTableCache();
        const length = formatInteger(cached.pageLength);
        console.log(`cached ${cached.url} — ${length} characters → ${cached.pagePath}`);
    } else if (command === "freeze") {
        const frozen = writeFrozenSkillTable();
        const moved = frozen.hasMoved ? "froze" : "unchanged:";
        console.log(
            `${moved} ${formatInteger(frozen.count)} skills → ${FROZEN_PATH}, ` +
                `${formatInteger(frozen.auras)} reaching a side → ${FROZEN_AURA_PATH}, and ` +
                `${formatInteger(frozen.granted)} granting a blow → ${FROZEN_BLOWS_PATH}`,
        );
    } else {
        throw new SkillTableError(`unknown command "${command ?? ""}" — status, fetch or freeze`);
    }
}
