/**
 * The statuses a combatant's `buffs` mask is read by, lifted from the production bundle. A payload
 * restates the mask as one integer per combatant, and the client turns it into icons by walking
 * one bit per registered status, so the order they are registered in is what a bit means. Names
 * only: the sentences the game composes from them stay in the cache (`NOTICE.md`).
 *
 *     deno task margonem:statuses [freeze]
 */

import { assert } from "@std/assert";
import { encodeJson } from "#/libs/json-text.ts";
import { formatInteger } from "#/libs/number-text.ts";
import {
    isWhitespaceAt,
    LiteralTooLong,
    lookupEndOfRun,
    lookupQuotedLiteral,
    type QuotedLiteral,
    RUN_CHARACTERS_MAXIMUM,
} from "#/libs/text-walk.ts";
import { STATUS_BITS_MAXIMUM } from "#/src/core/carried-status.ts";
import { MARGONEM_CHANNEL, readCachedBuild, readCachedBundle } from "./margonem-client-source.ts";
import { type FrozenFiles, prepareFrozenFiles, writeFrozenFiles } from "./frozen-files.ts";
import { StatusBitTableError } from "./margometer-tool-error.ts";

/**
 * ⚠️ **The array is matched by shape, and a minifier is why.** The development bundle names it
 * `buffNames`; production build `Bb28FQty` calls it `ae`, so a name-anchored walk would read the
 * table off a channel that decides nothing. No build renames the entry: a name, nothing, a class.
 * The development bundle is unminified, so space may stand between the arguments.
 */
const NOTHING_ARGUMENT = "null";
const ARGUMENT_SEPARATOR = ",";
const ROLE = "buff";
const CALL_OPEN = "(";
const CALL_CLOSE = ")";
/**
 * Past the number of places `null` occurs in a bundle, so the walk stays bounded: 3,989 in
 * production `Bb28FQty` and 4,081 in development `CzdTQ32j` (2026-09-27).
 */
export const LOOKS_MAXIMUM = 65_536;
/** Past the distance from an entry's opening bracket to its arguments, for the same reason. */
const WALK_BACK_MAXIMUM = 256;
const FROZEN_PATH = "frozen/status-bits.ts";
/** The field the reading is dated by, exported so a test holds the frozen file to it. */
export const FROZEN_DATE_FIELD = "gameBuild";
/** What stands over the frozen table, exported so a guard holds the file to its generator. */
export const FROZEN_STATUS_BANNER =
    `// Generated by \`deno task margonem:statuses freeze\`. Do not edit by hand.
//
// The statuses a combatant's \`buffs\` mask is read by, in the order the client registers
// them, so the position is the bit. \`tools/status-bit-table.ts\` says what they are lifted from.
`;

/** The bit order written to `frozen/`, where it moved. */
export function writeFrozenStatusBits(): FrozenFiles {
    const frozen = prepareFrozenStatusBits();
    writeFrozenFiles(frozen);
    return frozen;
}

/** The bit order the cached bundle gives, dated by the first build that gave it (ADR 0011). */
export function prepareFrozenStatusBits(): FrozenFiles {
    const build = readCachedBuild();
    const bits = requireStatusBits(readCachedBundle(MARGONEM_CHANNEL.production));
    assert(bits.length > 0, "a table that is frozen counts something");
    return prepareFrozenFiles(
        [FROZEN_PATH],
        FROZEN_DATE_FIELD,
        build,
        bits.length,
        (date) => [encodeFrozenStatusModule(date, bits)],
    );
}

export function encodeFrozenStatusModule(build: string, bits: readonly string[]): string {
    const written = bits.map((name) => `        ${encodeRequiredText(name)},`).join("\n");
    assert(written.length > 0, "a table that is written down says something");
    assert(build.length > 0, "and is dated by the build it was lifted from");
    return `${FROZEN_STATUS_BANNER}
export const FROZEN_STATUS_BITS = {
    ${FROZEN_DATE_FIELD}: ${encodeRequiredText(build)},
    bits: [
${written}
    ],
} as const;
`;
}

/** One bit's name as the text it is written down as, or a refusal branded as this tool's. */
function encodeRequiredText(name: string): string {
    const text = encodeJson(name, 0);
    if (text instanceof Error) {
        throw new StatusBitTableError("a name of the table cannot be written", { cause: text });
    }
    return text;
}

/**
 * Every status the client registers, in source order, which is bit order. A build registering
 * none is one this walk no longer recognises, and it refuses rather than freezing an empty table:
 * an empty reading looks exactly like a game that dropped the feature.
 */
export function requireStatusBits(bundle: string): string[] {
    const names: string[] = [];
    let nothingAt = bundle.indexOf(NOTHING_ARGUMENT);
    for (let look = 0; look < LOOKS_MAXIMUM; look += 1) {
        if (nothingAt === -1) break;
        const name = lookupRegisteredStatusName(bundle, nothingAt);
        if (name !== null) {
            if (names.length === STATUS_BITS_MAXIMUM) {
                throw new StatusBitTableError(
                    `more than the ${STATUS_BITS_MAXIMUM} statuses a mask holds bits for`,
                );
            }
            names.push(name);
        }
        nothingAt = bundle.indexOf(NOTHING_ARGUMENT, nothingAt + 1);
    }
    if (nothingAt !== -1) {
        throw new StatusBitTableError(
            `more than ${LOOKS_MAXIMUM} places to look — the walk would stop short of the bundle`,
        );
    }
    if (names.length === 0) {
        throw new StatusBitTableError("no status is registered in the bundle — the client changed");
    }
    const twice = names.find((name, position) => names.indexOf(name) !== position);
    if (twice !== undefined) {
        throw new StatusBitTableError(
            `\`${twice}\` is registered at two bits — the client changed`,
        );
    }
    return names;
}

/**
 * The name registered by the entry whose `null` sits at `nothingAt`, or null where that is some
 * other call. Read forwards from the bracket rather than back from the comma: a literal is a
 * literal only where something says where it opened, and the bracket is that thing.
 */
function lookupRegisteredStatusName(bundle: string, nothingAt: number): string | null {
    assert(nothingAt >= 0, "an entry is looked for inside the bundle");
    const after = requireEndOfWhitespace(bundle, nothingAt + NOTHING_ARGUMENT.length);
    if (bundle.charAt(after) !== ARGUMENT_SEPARATOR) return null;
    const role = requireQuotedLiteral(bundle, requireEndOfWhitespace(bundle, after + 1));
    if (role === null) return null;
    if (role.text !== ROLE) return null;
    if (bundle.charAt(requireEndOfWhitespace(bundle, role.end)) !== CALL_CLOSE) return null;
    const separator = bundle.lastIndexOf(ARGUMENT_SEPARATOR, nothingAt);
    if (separator === -1) return null;
    if (requireEndOfWhitespace(bundle, separator + 1) !== nothingAt) return null;
    const open = bundle.lastIndexOf(CALL_OPEN, separator);
    if (open === -1) return null;
    if (open < nothingAt - WALK_BACK_MAXIMUM) return null;
    const name = requireQuotedLiteral(bundle, requireEndOfWhitespace(bundle, open + 1));
    if (name === null) return null;
    if (requireEndOfWhitespace(bundle, name.end) !== separator) return null;
    if (name.text.length === 0) return null;
    return name.text;
}

/** The literal opening at `open`, or null; refused where it runs past what a walk reads. */
function requireQuotedLiteral(bundle: string, open: number): QuotedLiteral | null {
    const literal = lookupQuotedLiteral(bundle, open);
    if (literal instanceof LiteralTooLong) {
        throw new StatusBitTableError(
            `a literal at ${open} runs past the ${literal.maximum} characters read`,
            { cause: literal },
        );
    }
    return literal;
}

/** Where a run of whitespace ends, refused where it runs past what a walk reads in one go. */
function requireEndOfWhitespace(bundle: string, from: number): number {
    const runEnd = lookupEndOfRun(bundle, from, RUN_CHARACTERS_MAXIMUM, isWhitespaceAt);
    if (runEnd === null) {
        throw new StatusBitTableError(
            `whitespace at ${from} runs past the ${RUN_CHARACTERS_MAXIMUM} characters read`,
        );
    }
    return runEnd;
}

if (import.meta.main) {
    if (Deno.args.includes("freeze")) {
        const frozen = writeFrozenStatusBits();
        const count = formatInteger(frozen.count);
        const moved = frozen.hasMoved ? "froze" : "unchanged:";
        console.log(`${moved} ${count} bits from build ${frozen.date} → ${FROZEN_PATH}`);
    } else {
        const bits = requireStatusBits(readCachedBundle(MARGONEM_CHANNEL.production));
        console.log(`${formatInteger(bits.length)} bits in build ${readCachedBuild()}`);
        for (const [index, name] of bits.entries()) {
            console.log(`  bit ${formatInteger(index)}  ${name}`);
        }
        console.log(`run with \`freeze\` to write ${FROZEN_PATH}`);
    }
}
